function arms = valueArms()
%VALUEARMS The Value arm names on the wire.

    arms = {'intValue', 'realValue', 'boolValue', 'stringValue', 'instanceId', ...
            'sequence', 'null', 'unset', 'quantity', 'enumLiteral', 'complex', ...
            'array', 'vector', 'vectorQuantity', 'measurementRef', 'infinity', ...
            'function', 'set', 'tensorQuantity', 'metaobject', 'undetermined'};
end
