function caps = capabilities()
%CAPABILITIES Return capability names and their wire values.

    caps = struct( ...
        'typeFacts', 'type_facts', ...
        'convert', 'convert', ...
        'verification', 'verification', ...
        'verificationQuestions', 'verification_questions', ...
        'query', 'query', ...
        'documentQuery', 'document_query', ...
        'renderDocument', 'render_document', ...
        'renderDocumentHtml', 'render_document_html', ...
        'renderView', 'render_view', ...
        'enumValues', 'enum_values', ...
        'evaluateSubject', 'evaluate_subject', ...
        'symbolAttributes', 'symbol_attributes', ...
        'unsetValue', 'unset_value', ...
        'featureValues', 'feature_values', ...
        'applyEdits', 'apply_edits', ...
        'authoring', 'authoring', ...
        'connectionAuthoring', 'connection_authoring', ...
        'satisfyAuthoring', 'satisfy_authoring', ...
        'requirementConstraintAuthoring', 'requirement_constraint_authoring', ...
        'transitionAuthoring', 'transition_authoring', ...
        'verificationObjectiveAuthoring', 'verification_objective_authoring', ...
        'metadataAuthoring', 'metadata_authoring', ...
        'metadataPrefixAuthoring', 'metadata_prefix_authoring', ...
        'sequenceAuthoring', 'sequence_authoring', ...
        'actionBodyStatementAuthoring', 'action_body_statement_authoring', ...
        'importAuthoring', 'import_authoring', ...
        'documentationAuthoring', 'documentation_authoring', ...
        'commentAuthoring', 'comment_authoring', ...
        'memberModifiers', 'member_modifiers', ...
        'implicitParameters', 'implicit_parameters', ...
        'constraintBodyAuthoring', 'constraint_body_authoring', ...
        'stateActionAuthoring', 'state_action_authoring', ...
        'editDocuments', 'edit_documents', ...
        'parseSources', 'parse_sources', ...
        'inlineLanguage', 'inline_language', ...
        'strictConformance', 'strict_conformance', ...
        'complexValues', 'complex_values', ...
        'structuredValues', 'structured_values', ...
        'measurementRefs', 'measurement_refs', ...
        'functionValues', 'function_values', ...
        'setValues', 'set_values', ...
        'tensorValues', 'tensor_values', ...
        'metaobjectValues', 'metaobject_values', ...
        'verificationVerdicts', 'verification_verdicts', ...
        'infinityValue', 'infinity_value', ...
        'diagnosticCodes', 'diagnostic_codes', ...
        'schedule', 'schedule', ...
        'caseEvaluations', 'case_evaluations', ...
        'scheduleExplore', 'schedule_explore', ...
        'performer', 'performer', ...
        'stateTrace', 'state_trace', ...
        'finalTime', 'final_time', ...
        'engines', 'engines', ...
        'undeterminedValue', 'undetermined_value', ...
        'bigIntValues', 'big_int_values', ...
        'rationalValues', 'rational_values');
end
