function result = exploreAnalysis(model, symbolId, varargin)
%EXPLOREANALYSIS Explore every outcome admitted for an analysis case.

    options = opensysml.internal.nameValueOptions(struct( ...
        'subject', '', 'arguments', {{}}, 'namedArguments', struct(), ...
        'schedule', 'explore'), varargin, 'exploreAnalysis');
    schedule = char(options.schedule);
    if ~(strcmp(schedule, 'explore') || strncmp(schedule, 'explore:', 8))
        opensysml.internal.raise('opensysml:argument', ...
            sprintf('schedule ''%s'' answers one run''s result, not every outcome: spell it ''explore'' or ''explore:runs=<n>,depth=<d>''', ...
            schedule));
    end
    model.connection.require('verification');
    scheduleCapabilities = opensysml.internal.runCapabilities(model.connection, schedule, '');
    arguments = opensysml.internal.encodeArguments(options.arguments, model.connection, ...
        'exploreAnalysis arguments');
    named = opensysml.internal.encodeNamedArguments(options.namedArguments, ...
        model.connection, 'exploreAnalysis namedArguments');
    request = struct('modelHash', model.hash, 'symbolId', char(symbolId), ...
        'arguments', {arguments}, 'namedArguments', named, 'schedule', schedule);
    if ~isempty(options.subject), request.subjectSymbolId = char(options.subject); end
    capabilities = [{'verification', 'complex_values', 'structured_values', ...
        'measurement_refs', 'set_values', 'tensor_values', 'metaobject_values'}, ...
        scheduleCapabilities];
    raw = opensysml.call(model.connection, 'RunAnalysis', request, capabilities);
    result = opensysml.internal.decodeExplorationResponse(raw, model.connection);
end
