function test_authoring_live()
%TEST_AUTHORING_LIVE Apply edits against a running sysml-grpc service.

    if isempty(getenv('OPENSYSML_SERVICE'))
        fprintf('authoring live: skipped (OPENSYSML_SERVICE unset)\n');
        return;
    end
    conn = opensysml.connect();
    source = sprintf([ ...
        'metadata def Safety;\n' ...
        'package Demo {\n' ...
        '    requirement def Requirement;\n' ...
        '    part def Other;\n' ...
        '    part def SC {\n' ...
        '        requirement r : Requirement;\n' ...
        '        attribute mass : ScalarValues::Real = 1.0;\n' ...
        '        part left;\n' ...
        '        part right;\n' ...
        '        part t;\n' ...
        '        part obsolete;\n' ...
        '        part discarded;\n' ...
        '        part movable;\n' ...
        '    }\n' ...
        '    action def Runner {\n' ...
        '        in count : ScalarValues::Integer;\n' ...
        '    }\n' ...
        '}\n']);
    model = opensysml.parseSource(conn, source, 'name', 'authoring.sysml');
    assert_equal(model.ok(), true, 'authoring fixture parses');

    increment = opensysml.Body();
    increment.addAssign('count', 'count + 1');
    loopBody = opensysml.Body();
    loopBody.addWhile('count < 2', increment);
    editor = model.edit();
    editor.setValue('Demo::SC::mass', '2.0');
    editor.rename('Demo::SC::obsolete', 'retired');
    editor.addMember('Demo::SC', 'part', 'newPart', ...
        'metadata', {'Safety'}, 'doc', 'A newly authored part.');
    editor.addSatisfy('Demo::SC', 'Demo::SC::r', 'by', 'Demo::SC::t');
    editor.addImport('Demo', 'ScalarValues::*');
    editor.addDocumentation('Demo::SC::mass', 'Measured in kilograms.');
    editor.addComment('Demo::SC', 'Reviewed.', 'about', {'Demo::SC::mass'});
    editor.addConnection('Demo::SC', 'connection', 'left', 'right', 'name', 'link');
    editor.addIf('Demo::Runner', 'true', loopBody, 'then', false);
    editor.deleteElement('Demo::SC::discarded');
    editor.move('Demo::SC::movable', 'Demo::Other');
    edited = editor.apply();
    assert_equal(isa(edited, 'opensysml.EditResult'), true, 'EditResult type');
    assert_equal(isa(edited, 'opensysml.Conversion'), true, ...
        'EditResult Conversion base');
    assert_equal(isempty(edited.applied), false, 'applied edit records');
    assert_equal(isempty(edited.documents), false, 'edited document records');
    assert_equal(edited.documents{1}.name, 'authoring.sysml', ...
        'edited document name');
    assert_equal(~isempty(strfind(edited.content, 'mass : ScalarValues::Real = 2.0')), ...
        true, 'setValue output');
    assert_equal(~isempty(strfind(edited.content, 'part retired;')), true, ...
        'rename output');
    assert_equal(~isempty(strfind(edited.content, '#Safety part newPart')), true, ...
        'member metadata output');
    assert_equal(~isempty(strfind(edited.content, 'A newly authored part.')), true, ...
        'member documentation output');
    assert_equal(~isempty(strfind(edited.content, 'satisfy ')), ...
        true, 'satisfy output');
    assert_equal(~isempty(strfind(edited.content, 'private import ScalarValues::*;')), ...
        true, 'import output');
    assert_equal(~isempty(strfind(edited.content, 'Measured in kilograms.')), ...
        true, 'documentation output');
    assert_equal(~isempty(strfind(edited.content, 'Reviewed.')), true, ...
        'comment output');
    assert_equal(~isempty(strfind(edited.content, 'connection link connect left to right;')), ...
        true, 'connection output');
    assert_equal(~isempty(strfind(edited.content, 'while count < 2')), true, ...
        'nested while output');
    assert_equal(~isempty(strfind(edited.content, 'if true')), true, ...
        'outer if output');
    assert_equal(~isempty(strfind(edited.content, 'part movable')), true, ...
        'move output retains moved declaration');
    assert_equal(~isempty(strfind(edited.content, 'part discarded')), false, ...
        'delete output');
    reparsed = opensysml.parseSource(conn, edited.content, ...
        'name', 'authoring-edited.sysml');
    assert_equal(reparsed.ok(), true, 'edited document reparses');
    assert_equal(isa(reparsed.find('newPart'), 'opensysml.Symbol'), true, ...
        'reparsed added member');
    assert_equal(isa(reparsed.get('Demo::Other::movable'), 'opensysml.Symbol'), true, ...
        'reparsed moved member');
    expect_error(@() editor.apply(), 'opensysml:argument');
    savePath = [tempname(fileparts(mfilename('fullpath'))) '.sysml'];
    saveCleanup = onCleanup(@() deleteIfPresent(savePath));
    edited.save(savePath);
    assert_equal(exist(savePath, 'file'), 2, 'EditResult.save output');
    assert_equal(strcmp(fileread(savePath), edited.content), true, ...
        'EditResult.save content');
    clear saveCleanup;

    stateSource = sprintf([ ...
        'package StateDemo {\n' ...
        '    attribute def CycleStart;\n' ...
        '    attribute def CycleEnd;\n' ...
        '    state def Machine;\n' ...
        '}\n']);
    states = opensysml.parseSource(conn, stateSource, 'name', 'states.sysml');
    stateResult = states.edit();
    stateResult.addState('StateDemo::Machine', 'idle');
    stateResult.addState('StateDemo::Machine', 'running');
    stateResult.addEntryTransition('StateDemo::Machine', 'idle');
    stateResult.addTransition('StateDemo::Machine', 'idle', 'running', ...
        'name', 'start', 'trigger', 'CycleStart');
    transitionResult = stateResult.apply();
    assert_equal(~isempty(strfind(transitionResult.content, ...
        'entry; then idle;')), true, 'entry transition');
    assert_equal(~isempty(strfind(transitionResult.content, ...
        'transition start first idle accept CycleStart then running;')), ...
        true, 'state transition');
    stateReparsed = opensysml.parseSource(conn, transitionResult.content, ...
        'name', 'states-edited.sysml');
    assert_equal(stateReparsed.ok(), true, 'transition document reparses');

    sourceA = 'package Alpha { part def Base; }';
    sourceB = 'package Beta { part def Child :> Alpha::Base; }';
    multiple = opensysml.parseSources(conn, ...
        {{'alpha.sysml', sourceA}, {'beta.sysml', sourceB}}, 'language', 'sysml');
    multiEditor = multiple.edit();
    multiEditor.rename('Alpha::Base', 'NewBase');
    multiResult = multiEditor.apply();
    assert_equal(isempty(multiResult.content), true, ...
        'multi-document content is not flattened');
    assert_equal(numel(multiResult.documents), 2, ...
        'multi-document results include both documents');
    editedSources = cell(1, numel(multiResult.documents));
    for i = 1:numel(multiResult.documents)
        document = multiResult.documents{i};
        editedSources{i} = {document.name, document.content};
    end
    multiReparsed = opensysml.parseSources(conn, editedSources, 'language', 'sysml');
    assert_equal(multiReparsed.ok(), true, 'edited documents reparse together');
    assert_equal(containsAny(multiResult.documents, 'part def NewBase;'), ...
        true, 'declaration document changed');
    assert_equal(containsAny(multiResult.documents, 'Alpha::NewBase'), ...
        true, 'referencing document changed');

    unknown = opensysml.parseSource(conn, 'part def P;', 'name', 'unknown.sysml');
    unknownEditor = unknown.edit();
    unknownEditor.setValue('Missing::value', '1');
    expect_typed_error(@() unknownEditor.apply(), ...
        'opensysml:diagnostics:edit:unknownTarget', 'EDIT_FAILURE_UNKNOWN_TARGET');

    referenced = opensysml.parseSource(conn, ...
        'package P { part def Base; part def Child :> Base; }', ...
        'name', 'referenced.sysml');
    deleteEditor = referenced.edit();
    deleteEditor.deleteElement('P::Base');
    expect_typed_error(@() deleteEditor.apply(), ...
        'opensysml:diagnostics:edit:deleteReferenced', ...
        'EDIT_FAILURE_DELETE_REFERENCED');
    duplicateEditor = referenced.edit();
    duplicateEditor.addPartDef('P', 'Base');
    expect_typed_error(@() duplicateEditor.apply(), ...
        'opensysml:diagnostics:edit:memberNameTaken', ...
        'EDIT_FAILURE_MEMBER_NAME_TAKEN');

    fprintf('authoring live ok\n');
end

function tf = containsAny(documents, text)
    tf = false;
    for i = 1:numel(documents)
        if ~isempty(strfind(documents{i}.content, text))
            tf = true;
            return;
        end
    end
end

function expect_typed_error(fn, identifier, failure)
    expect_error(fn, identifier);
    err = opensysml.lastError();
    assert_equal(err.details.failure, failure, 'typed edit failure');
end

function expect_error(fn, identifier)
    try
        fn();
    catch e
        if strcmp(e.identifier, identifier), return; end
        error('assert:error', 'got %s, want %s', e.identifier, identifier);
    end
    error('assert:error', 'expected %s', identifier);
end

function deleteIfPresent(path)
    if exist(path, 'file'), delete(path); end
end
