function test_rendered_view()
%TEST_RENDERED_VIEW Decode all RenderView fields and absent messages.
    answer = struct( ...
        'view', 'Demo::view', ...
        'kind', 'interconnection', ...
        'stated', 'rendered', ...
        'nodes', struct( ...
            'id', 'n0', 'kind', 'part', 'name', 'root', ...
            'nameSynthesized', true, 'type', 'Demo::Part', 'detail', 'detail', ...
            'text', 'text', 'standIn', true, 'parent', '', ...
            'ports', struct('id', 'n0.0', 'name', 'api', ...
                'type', 'Demo::API', 'direction', 'inout'), ...
            'origin', struct('file', 'views.sysml', 'startLine', 4), ...
            'geometry', struct('x', 1, 'y', 2, 'width', 3, 'height', 4, ...
                'hasSize', true, 'collapsed', true), ...
            'style', struct('fill', '#fff', 'line', '#000', 'text', '#111', ...
                'font', 'sans', 'fontSize', 12, 'bold', true, 'italic', true)), ...
        'edges', struct('from', 'n0', 'to', 'n1', 'fromPort', 'n0.0', ...
            'toPort', 'n1.0', 'label', 'wire', 'name', 'wire', ...
            'kind', 'connection', 'origin', [], 'route', struct('x', 2, 'y', 3), ...
            'style', struct('line', '#222')), ...
        'columns', {{'a'}}, ...
        'rows', struct('cells', {{'x'}}, 'origin', []), ...
        'canvas', struct('unit', 'px', 'width', 800, 'height', 400, 'hasSize', true), ...
        'notes', struct('text', 'note', 'anchor', 'n0', 'edgeFrom', 'n0', ...
            'edgeTo', 'n1', 'x', 1, 'y', 2, 'width', 3, 'height', 4, ...
            'hasSize', true, 'origin', []), ...
        'notices', {{'notice'}});
    rendered = opensysml.RenderedView(answer);
    assert(strcmp(rendered.view, 'Demo::view'));
    assert(rendered.nodes.nameSynthesized);
    assert(strcmp(rendered.nodes.ports.direction, 'inout'));
    assert(rendered.nodes.origin.startLine == 4);
    assert(rendered.nodes.geometry.collapsed);
    assert(rendered.nodes.style.fontSize == 12);
    assert(strcmp(rendered.edges.fromPort, 'n0.0'));
    assert(rendered.edges.route.x == 2);
    assert(strcmp(rendered.rows.cells{1}, 'x'));
    assert(rendered.canvas.hasSize);
    assert(strcmp(rendered.notes.edgeTo, 'n1'));
    assert(strcmp(rendered.notices{1}, 'notice'));

    empty = opensysml.RenderedView(struct());
    assert(isempty(empty.canvas));
    assert(isempty(empty.nodes));
end
