package usage

import (
	"flag"
	"fmt"
	"io"
	"strings"
)

// manLiteralWidth is what an example block has of an 80-column terminal, once
// the page has indented the body and the block has indented again.
const manLiteralWidth = 71

// ManMeta is the page's title line: the date it documents, the project the
// command belongs to, and the manual it is part of.
type ManMeta struct {
	Date   string
	Source string
	Manual string
}

// WriteRoff writes the man page for the command in the man macro package, from
// the same description the terminal help is rendered from.
func (d Doc) WriteRoff(w io.Writer, fs *flag.FlagSet, meta ManMeta) {
	fmt.Fprintf(w, ".\\\" Generated by %q; edit the description in the command's usage.go.\n", d.Command+" -man")
	fmt.Fprintf(w, ".TH %s %d %q %q %q\n", strings.ToUpper(d.Command), d.Section(), meta.Date, meta.Source, meta.Manual)

	fmt.Fprintf(w, ".SH NAME\n%s \\- %s\n", roffEscape(d.Command), roffEscape(d.Summary))

	fmt.Fprintf(w, ".SH SYNOPSIS\n")
	for i, form := range d.Synopsis {
		if i > 0 {
			fmt.Fprintf(w, ".br\n")
		}
		fmt.Fprintf(w, ".B %s\n%s\n", roffEscape(d.Command), roffText(form))
	}

	if len(d.Description) > 0 {
		fmt.Fprintf(w, ".SH DESCRIPTION\n")
		writeParagraphs(w, d.Description, true)
	}

	fmt.Fprintf(w, ".SH OPTIONS\n")
	writeOptions(w, fs)

	for _, sec := range d.Sections {
		fmt.Fprintf(w, ".SH %s\n", roffEscape(strings.ToUpper(sec.Title)))
		writeParagraphs(w, sec.Lead, true)
		writeRoffExamples(w, sec.Examples, len(sec.Lead) == 0)
		for _, item := range sec.Items {
			fmt.Fprintf(w, ".TP\n.B %s\n%s\n", roffEscape(item.Label), roffText(item.Text))
		}
		writeParagraphs(w, sec.Paragraphs, len(sec.Lead)+len(sec.Examples)+len(sec.Items) == 0)
	}

	if len(d.SeeAlso) > 0 {
		fmt.Fprintf(w, ".SH SEE ALSO\n%s\n", roffText(strings.Join(d.SeeAlso, ", ")))
	}
}

// writeOptions describes every flag the command declares, in the order the flag
// set visits them, so a flag cannot be documented only in the help.
func writeOptions(w io.Writer, fs *flag.FlagSet) {
	fs.VisitAll(func(f *flag.Flag) {
		placeholder, help := flag.UnquoteUsage(f)
		fmt.Fprintf(w, ".TP\n")
		if placeholder == "" {
			fmt.Fprintf(w, ".B \\-%s\n", roffEscape(f.Name))
		} else {
			fmt.Fprintf(w, ".BI \\-%s \" %s\"\n", roffEscape(f.Name), roffEscape(placeholder))
		}
		if !isZeroDefault(f.DefValue) {
			help = sentence(help) + " The default is " + f.DefValue + "."
		}
		fmt.Fprintf(w, "%s\n", roffText(help))
	})
}

// sentence ends a flag's usage string so a sentence may follow it.
func sentence(text string) string {
	text = strings.TrimRight(text, " ")
	if text == "" || strings.ContainsAny(text[len(text)-1:], ".!?:") {
		return text
	}
	return text + "."
}

// isZeroDefault reports whether a default value is the type's zero, which the
// flag package's own help omits.
func isZeroDefault(value string) bool {
	switch value {
	case "", "0", "false", "0s":
		return true
	}
	return false
}

// writeRoffExamples writes the commands as an indented literal block, so the
// spacing a reader would type survives filling.
func writeRoffExamples(w io.Writer, examples []Example, opensSection bool) {
	if len(examples) == 0 {
		return
	}
	width := commandWidth(examples, manLiteralWidth)
	aligned := fitsAligned(examples, width)
	if !opensSection {
		fmt.Fprintf(w, ".PP\n")
	}
	fmt.Fprintf(w, ".RS 2\n.nf\n")
	for _, ex := range examples {
		folded := foldCommand(ex.Command, manLiteralWidth)
		if len(folded) > 1 {
			if ex.Comment != "" {
				fmt.Fprintf(w, "# %s\n", roffEscape(ex.Comment))
			}
			for _, line := range folded {
				fmt.Fprintf(w, "%s\n", roffEscape(line))
			}
			continue
		}
		if ex.Comment == "" {
			fmt.Fprintf(w, "%s\n", roffEscape(ex.Command))
			continue
		}
		if !aligned {
			fmt.Fprintf(w, "# %s\n%s\n", roffEscape(ex.Comment), roffEscape(ex.Command))
			continue
		}
		padding := strings.Repeat(" ", width-len(ex.Command))
		fmt.Fprintf(w, "%s%s  # %s\n", roffEscape(ex.Command), padding, roffEscape(ex.Comment))
	}
	fmt.Fprintf(w, ".fi\n.RE\n")
}

// fitsAligned reports whether every commented example still fits an indented
// literal line once its comment is aligned, since roff does not fill one.
func fitsAligned(examples []Example, width int) bool {
	for _, ex := range examples {
		if ex.Comment == "" || len(ex.Command) > manLiteralWidth {
			continue
		}
		if width+4+len(ex.Comment) > manLiteralWidth {
			return false
		}
	}
	return true
}

// writeParagraphs writes prose as filled paragraphs. A section header already
// breaks the first one, and mandoc warns about a paragraph macro after it.
func writeParagraphs(w io.Writer, paragraphs []string, opensSection bool) {
	for i, para := range paragraphs {
		if i > 0 || !opensSection {
			fmt.Fprintf(w, ".PP\n")
		}
		fmt.Fprintf(w, "%s\n", roffText(para))
	}
}

// roffText renders prose: escaped, and refilled so no source line is long
// enough to be awkward to diff.
func roffText(text string) string {
	return breakLines(roffEscape(collapse(text)))
}

// collapse reduces the whitespace of a paragraph to single spaces, since roff
// fills the text itself.
func collapse(text string) string {
	return strings.Join(strings.Fields(text), " ")
}

// roffEscape hides the characters roff reads as its own: the escape character,
// a hyphen meaning itself, a leading control character, and non-ASCII.
func roffEscape(text string) string {
	var out strings.Builder
	for _, r := range text {
		switch {
		case r == '\\':
			out.WriteString("\\e")
		case r == '-':
			out.WriteString("\\-")
		case r < 0x80:
			out.WriteRune(r)
		default:
			out.WriteString(roffRune(r))
		}
	}
	text = out.String()
	if strings.HasPrefix(text, ".") || strings.HasPrefix(text, "'") {
		text = "\\&" + text
	}
	return text
}

// roffRune names a character outside ASCII by the roff special character for it,
// falling back on its code point, which both groff and mandoc understand.
func roffRune(r rune) string {
	if name, ok := roffSpecials[r]; ok {
		return name
	}
	return fmt.Sprintf("\\[u%04X]", r)
}

// roffSpecials names the characters this project's prose uses by the classic
// roff escapes, which render on a terminal that cannot show the character.
var roffSpecials = map[rune]string{
	'—': "\\(em",
	'–': "\\(en",
	'“': "\\(lq",
	'”': "\\(rq",
	'‘': "\\(oq",
	'’': "\\(cq",
	'…': "\\&...",
	'§': "\\(sc",
	'·': "\\(bu",
	'×': "\\(mu",
	'≤': "\\(<=",
	'≥': "\\(>=",
	'→': "\\(->",
	'≠': "\\(!=",
}

// breakLines wraps already-escaped prose at word boundaries, never leaving a
// line that begins with a control character.
func breakLines(text string) string {
	wrapped := Wrap(text, textWidth)
	lines := strings.Split(wrapped, "\n")
	for i, line := range lines {
		if strings.HasPrefix(line, ".") || strings.HasPrefix(line, "'") {
			lines[i] = "\\&" + line
		}
	}
	return strings.Join(lines, "\n")
}
