// The isomorphic core: everything that does not need a process to spawn.

export { Connection } from "./connection.js";
export type {
  ConnectionBackend,
  Encoding,
  ResponseTap,
  TransportOptions,
} from "./connection.js";
export type { WasmHost } from "./wasm.js";
export { Instance, InstanceTree, Model, ModelSymbol, decodeDiagnostic } from "./model.js";
export type {
  AttributeFacts,
  EvalOptions,
  FeatureValue,
  Multiplicity,
  ParseOptions,
  SpecializationFacts,
  TypeFacts,
} from "./model.js";
export { LANGUAGES, SourceDocument, sourceDocuments } from "./sources.js";
export type { Source } from "./sources.js";
export {
  Conversion,
  EXPERIMENTAL_NOTICE,
  FORMAT_API_JSON,
  FORMAT_SYSML,
  FORMAT_TURTLE,
  MIGRATED_NOT_CONVERTED,
  MIGRATION_NOTICE,
  Migration,
  MigrationReport,
  formatOfPath,
  isExperimental,
  isV1,
  migrationReportOf,
  pathIsV1,
} from "./conversion.js";
export type { MigrateOptions, MigrationEntry } from "./conversion.js";
export {
  QueryElement,
  TYPE_COMPOSITE_CONSTRAINT,
  TYPE_PRIMITIVE_CONSTRAINT,
  TYPE_QUERY,
  buildQuery,
} from "./query.js";
export type { ConstraintPayload, QueryForm, QueryPayload, ScopeEntry } from "./query.js";
export {
  DocumentQueryResult,
  DocumentRow,
  DocumentEvent,
  documentEventOf,
  DocumentState,
  DocumentVerdict,
  ElementRef,
  ObjectRef,
  buildBindings,
} from "./document.js";
export type { BindingValues, DocumentValue } from "./document.js";
export type {
  RenderCanvas,
  RenderEdge,
  RenderGeometry,
  RenderNode,
  RenderNote,
  RenderPoint,
  RenderPort,
  RenderRow,
  RenderSpan,
  RenderStyle,
  RenderedView,
} from "./render-view.js";
export {
  ENGINE_ALL,
  ENGINE_AUTO,
  STRENGTH_BOUNDED,
  STRENGTH_NOT_COVERED,
  STRENGTH_OBSERVED,
  STRENGTH_PROVED,
  STRENGTH_WITNESSED,
  engineInfoOf,
  explainEngine,
  explainStanding,
  standingOf,
  standingReached,
  standingReported,
} from "./engines.js";
export type { EngineBound, EngineInfo, Standing } from "./engines.js";
export { Exploration, Outcome } from "./exploration.js";
export type { OutcomeValues } from "./exploration.js";
export {
  AppliedEdit,
  Body,
  EditedDocument,
  EditRequestBuilder,
  EditResult,
  Editor,
  editErrorOf,
  editResultOf,
  errorForFailure,
  failureName,
  referrersOf,
} from "./edit.js";
export type { EditOperationData, EditTarget } from "./edit.js";
export {
  AnalysisResult,
  CalcResult,
  CaseEvaluation,
  KIND_ASSERTION,
  KIND_CONSTRAINT,
  KIND_OBJECT,
  KIND_OBJECTIVE,
  KIND_REQUIREMENT,
  KIND_SATISFY,
  QUESTION_EVALUATE,
  QUESTION_HOLDS,
  QUESTION_SATISFIABLE,
  STATUS_HOLDS,
  STATUS_SATISFIABLE,
  STATUS_UNDECIDED,
  STATUS_UNSATISFIABLE,
  STATUS_VIOLATED,
  SweepRow,
  SweepTable,
  Validation,
  VERDICT_ERROR,
  VERDICT_FAIL,
  VERDICT_INCONCLUSIVE,
  VERDICT_PASS,
  explainVerificationVerdict,
  explainVerdict,
  raiseVerdictError,
  verificationPassed,
  verdictEvaluated,
  verdictHolds,
} from "./verdict.js";
export type { Verdict } from "./verdict.js";
export {
  CAPABILITY_APPLY_EDITS,
  CAPABILITY_ACTION_BODY_STATEMENT_AUTHORING,
  CAPABILITY_CASE_EVALUATIONS,
  CAPABILITY_COMPLEX_VALUES,
  CAPABILITY_BIG_INT_VALUES,
  CAPABILITY_CONVERT,
  CAPABILITY_CONVERT_DOCUMENTS,
  CAPABILITY_PARSE_SOURCES_AFFECTED,
  CAPABILITY_MIGRATE,
  CAPABILITY_DIAGNOSTIC_CODES,
  CAPABILITY_EDIT_DOCUMENTS,
  CAPABILITY_ENGINES,
  CAPABILITY_ENUM_VALUES,
  CAPABILITY_EVALUATE_SUBJECT,
  CAPABILITY_FEATURE_VALUES,
  CAPABILITY_FINAL_TIME,
  CAPABILITY_FUNCTION_VALUES,
  CAPABILITY_INFINITY_VALUE,
  CAPABILITY_INLINE_LANGUAGE,
  CAPABILITY_MEASUREMENT_REFS,
  CAPABILITY_METAOBJECT_VALUES,
  CAPABILITY_PERFORMER,
  CAPABILITY_STATE_TRACE,
  CAPABILITY_QUERY,
  CAPABILITY_SCHEDULE,
  CAPABILITY_SCHEDULE_EXPLORE,
  CAPABILITY_SEQUENCE_AUTHORING,
  CAPABILITY_SET_VALUES,
  CAPABILITY_STRICT_CONFORMANCE,
  CAPABILITY_STRUCTURED_VALUES,
  CAPABILITY_UNDETERMINED_VALUE,
  CAPABILITY_VERIFICATION_VERDICTS,
  CAPABILITY_SYMBOL_ATTRIBUTES,
  CAPABILITY_TENSOR_VALUES,
  CAPABILITY_TYPE_FACTS,
  CAPABILITY_UNSET_VALUE,
  CAPABILITY_VERIFICATION,
  CAPABILITY_AUTHORING,
  CAPABILITY_COMMENT_AUTHORING,
  CAPABILITY_CONNECTION_AUTHORING,
  CAPABILITY_CONSTRAINT_BODY_AUTHORING,
  CAPABILITY_DOCUMENTATION_AUTHORING,
  CAPABILITY_DOCUMENT_QUERY,
  CAPABILITY_IMPLICIT_PARAMETERS,
  CAPABILITY_IMPORT_AUTHORING,
  CAPABILITY_MEMBER_MODIFIERS,
  CAPABILITY_METADATA_AUTHORING,
  CAPABILITY_METADATA_PREFIX_AUTHORING,
  CAPABILITY_PARSE_SOURCES,
  CAPABILITY_RENDER_DOCUMENT,
  CAPABILITY_RENDER_DOCUMENT_HTML,
  CAPABILITY_REQUIREMENT_CONSTRAINT_AUTHORING,
  CAPABILITY_SATISFY_AUTHORING,
  CAPABILITY_STATE_ACTION_AUTHORING,
  CAPABILITY_TRANSITION_AUTHORING,
  CAPABILITY_VERIFICATION_OBJECTIVE_AUTHORING,
  CAPABILITY_VERIFICATION_QUESTIONS,
  MissingCapabilityError,
  ServerInfo,
  capabilityRefusal,
  mismatchReason,
  requireCapability,
  upgradeRemedy,
} from "./capabilities.js";
export {
  AnalysisRunError,
  ChecksumMismatchError,
  ClosedConnectionError,
  ConversionError,
  DeleteReferencedError,
  DocumentQueryError,
  DownloadError,
  EditError,
  EditResultError,
  EditTargetError,
  EvaluationError,
  ExecutionError,
  FeatureValueError,
  IllegalMemberKindError,
  InstanceTypeError,
  InvalidEditError,
  InvalidRequestError,
  MemberNameTakenError,
  MigrationError,
  MoveReferencedError,
  NoEditsError,
  OverlappingEditsError,
  OwnerInsideTargetError,
  OwnerNotFoundError,
  OwnerNotNamespaceError,
  ReferencedElsewhereError,
  Referrer,
  RenameReferencedError,
  MalformedValueError,
  ManifestSignatureError,
  ModelFileNotFoundError,
  ModelNotFoundError,
  OpenSysMLError,
  ParseError,
  QueryError,
  ServiceError,
  ServiceStartError,
  ServiceTimeoutError,
  ServiceUnavailableError,
  StaleServiceError,
  SymbolNotFoundError,
  TypeMismatchError,
  UnpinnedReleaseError,
  UnsignedReleaseError,
  UnsupportedOperationError,
  UnsupportedValueError,
  WrongKindError,
} from "./errors.js";
export type { FailureCause, ModelDiagnostic } from "./errors.js";
export {
  TypedObject,
  asBoolean,
  asComplex,
  asEnum,
  asInt,
  asObject,
  asQuantity,
  asReal,
  asString,
  asTyped,
  featureValue,
  listFeatureValue,
  optionalFeatureValue,
  registerTyped,
} from "./typed.js";
export type {
  FeatureDecoder,
  InstanceResolver,
  Quantity,
  TypedObjectClass,
} from "./typed.js";
export { callRpc, fromHandshakeError, fromRpcError, statusName } from "./status.js";
export type { NotFoundSubject, UnimplementedMapping } from "./status.js";
export {
  decodeValue,
  decodeVerdict,
  decodeStanding,
  encodeValue,
  formatValue,
  requireInput,
  toValue,
  valuesEqual,
} from "./values.js";
export type {
  ArrayValue,
  ComplexValue,
  EnumValue,
  FunctionValue,
  Magnitude,
  MeasurementRefValue,
  MetaobjectValue,
  QuantityValue,
  SysMLValue,
  SysMLVerdict,
  ValueInput,
  VerdictBound,
  VerdictStanding,
  VerificationVerdict,
  WitnessAssignment,
  TensorQuantityValue,
  UndeterminedValue,
  UnitFactor,
  UnitFactorization,
  VerdictSubject,
} from "./values.js";
export { baseUrl } from "./transport.js";
export { PACKAGE_NAME, PLATFORM_PACKAGE_PREFIX } from "./package.js";
export { SysMLService } from "../generated/sysml_pb.js";
