"""Generate statically typed Python classes from a SysML model.

Usage::

    python -m opensysml.generate model.sysml -o model_types.py

The generated module contains one class per SysML definition, deriving from
:class:`opensysml.typed.TypedObject`, with one property per feature. Output is a
runtime ``.py`` (no separate stub): the properties both carry the static type and
perform the runtime delegation to the Tier 1 instance, so a single artifact stays
in step with itself. Emission is deterministic — symbols are ordered by
fully-qualified name and nothing environment-dependent is written — so the output
can be committed as a golden file, and ``--check`` can gate that it is current.
"""

import argparse
import hashlib
import json
import keyword
import os
import sys
from dataclasses import dataclass, field, replace
from typing import Callable, Dict, Iterable, List, Optional, Sequence, Tuple

from opensysml.capabilities import CAPABILITY_TYPE_FACTS, MissingCapabilityError, require
from opensysml.typefacts import Multiplicity, Specialization, SymbolFacts, TypeFacts

GENERATED_HEADER = "# Generated by opensysml.generate. Do not edit."

# Decoder for a feature whose SysML type has no sound Python type.
_OBJECT_DECODER = "_t.as_object"

# Emission schema, bumped when this generator's output changes for an unchanged
# model. Not the opensysml release version, which would churn every module.
GENERATOR_VERSION = "4"

# The stamp hashes the model source client-side. A path, a timestamp or the
# service version would churn without the module's content changing.
MODEL_HASH_ALGORITHM = "sha256"

# What a module rendered without the model source says, so it cannot be mistaken
# for one stamped with a real hash.
UNSTAMPED = "unstamped"

# Definition kinds get a class; these usage kinds become properties on the
# enclosing class. Behavioral and connector usages (action, state, calc,
# constraint, requirement, connection, flow, interface, allocation, case) are
# not instance feature values and are skipped — see clients/python/README.md.
FEATURE_KINDS = frozenset(
    {
        "attributeusage",
        "partusage",
        "itemusage",
        "occurrenceusage",
        "individualusage",
        "portusage",
        "enumusage",
    }
)

# The generalization edges that make one element a kind of another. A typing edge
# is the element's type, not a supertype of it, so it is not one of these.
GENERALIZATION_KINDS = frozenset({"specializes", "subsets", "redefines"})

# How far a generalization chain is followed for a fact a declaration leaves out.
MAX_GENERALIZATION_DEPTH = 16

PRIMITIVE_TYPES = {
    "Boolean": "bool",
    "String": "str",
    "Natural": "int",
    "Integer": "int",
    "Rational": "float",
    "Real": "float",
    "Complex": "complex",
}

# Library scalars with no sound Python counterpart, mapped to `object`: Number is
# the supertype of every numeric scalar, so a Number slot may hold any of them.
UNMAPPED_PRIMITIVES = frozenset({"Number"})

# Members TypedObject itself provides; a property of the same name would shadow
# the machinery the accessors use, so such a feature is renamed.
RESERVED_MEMBERS = frozenset(
    {"instance", "from_instance", "unchecked", "sysml_id", "_instance"}
)


def is_definition_kind(kind: str) -> bool:
    """Whether a symbol kind declares a type, e.g. ``partDef`` or ``metaclass``."""
    lowered = kind.lower()
    return lowered.endswith("def") or lowered == "metaclass"


def is_feature_kind(kind: str) -> bool:
    """Whether a symbol kind is a usage exposed as an instance feature."""
    return kind.lower() in FEATURE_KINDS


@dataclass(frozen=True)
class Feature:
    """One SysML feature to emit as a property."""

    facts: SymbolFacts

    @property
    def name(self) -> str:
        return self.facts.name


@dataclass(frozen=True)
class Definition:
    """One SysML definition to emit as a class."""

    facts: SymbolFacts
    features: Tuple[Feature, ...] = field(default_factory=tuple)

    @property
    def id(self) -> str:
        return self.facts.id

    @property
    def name(self) -> str:
        return self.facts.name

    @property
    def base_ids(self) -> Tuple[str, ...]:
        """FQNs of what this definition specializes, subsets or redefines, in
        declaration order, without repetition; each becomes a base class.
        """
        ordered: List[str] = []
        for spec in self.facts.specializations:
            if spec.kind in GENERALIZATION_KINDS and spec.target_id:
                if spec.target_id not in ordered:
                    ordered.append(spec.target_id)
        return tuple(ordered)


@dataclass(frozen=True)
class PythonType:
    """A rendered Python annotation plus the reason it was chosen, when notable."""

    annotation: str
    decoder: str
    comment: str = ""


def collect_definitions(root) -> List[Definition]:
    """Collect the definitions in a :class:`~opensysml.symbol.Symbol` tree, sorted by
    FQN, each feature taking the type and multiplicity it inherits.
    """
    definitions: List[Definition] = []
    facts_by_id: Dict[str, SymbolFacts] = {}
    _collect(root, definitions, facts_by_id)
    definitions = [_with_inherited_facts(definition, facts_by_id) for definition in definitions]
    definitions.sort(key=lambda definition: definition.id)
    return definitions


def _collect(symbol, out: List[Definition], facts_by_id: Dict[str, SymbolFacts]) -> None:
    children = symbol.children()
    facts = symbol.facts()
    facts_by_id[facts.id] = facts
    if is_definition_kind(symbol.kind):
        features = tuple(
            Feature(child.facts())
            for child in sorted(children, key=lambda child: child.id)
            if is_feature_kind(child.kind)
        )
        out.append(Definition(facts, features))
    for child in children:
        _collect(child, out, facts_by_id)


def _with_inherited_facts(
    definition: Definition, facts_by_id: Dict[str, SymbolFacts]
) -> Definition:
    """Fill in each feature's type and multiplicity from what it redefines."""
    features = tuple(
        Feature(_resolved_facts(feature.facts, facts_by_id)) for feature in definition.features
    )
    return Definition(definition.facts, features)


def _resolved_facts(
    facts: SymbolFacts, facts_by_id: Dict[str, SymbolFacts]
) -> SymbolFacts:
    """Return ``facts`` with the type and multiplicity it inherits filled in."""
    type_facts = facts.type
    if not _names_a_type(type_facts):
        inherited = _inherited(
            facts,
            facts_by_id,
            lambda other: other.type if _names_a_type(other.type) else None,
        )
        if inherited is not None:
            type_facts = _merged_type(type_facts, inherited)

    multiplicity = facts.multiplicity
    if multiplicity is None:
        multiplicity = _inherited(facts, facts_by_id, lambda other: other.multiplicity)

    if type_facts is facts.type and multiplicity is facts.multiplicity:
        return facts
    return replace(facts, type=type_facts, multiplicity=multiplicity)


def _inherited(
    facts: SymbolFacts,
    facts_by_id: Dict[str, SymbolFacts],
    pick: Callable[[SymbolFacts], Optional[object]],
    depth: int = 0,
):
    """First value ``pick`` yields walking what ``facts`` generalizes, nearest first."""
    if depth >= MAX_GENERALIZATION_DEPTH:
        return None
    for spec in facts.specializations:
        if spec.kind not in GENERALIZATION_KINDS or not spec.target_id:
            continue
        target = facts_by_id.get(spec.target_id)
        if target is None:
            continue
        found = pick(target)
        if found is not None:
            return found
        found = _inherited(target, facts_by_id, pick, depth + 1)
        if found is not None:
            return found
    return None


def _names_a_type(type_facts: Optional[TypeFacts]) -> bool:
    """Whether type facts name a type, as opposed to only classifying one."""
    return type_facts is not None and bool(type_facts.resolved_id or type_facts.declared)


def _merged_type(own: Optional[TypeFacts], inherited: TypeFacts) -> TypeFacts:
    """Take the type name from ``inherited``, keeping what the feature states itself."""
    if own is None:
        return inherited
    return replace(
        own,
        declared=inherited.declared,
        resolved_id=inherited.resolved_id,
        resolved_kind=inherited.resolved_kind,
        primitive=own.primitive or inherited.primitive,
        primitive_source=own.primitive_source or inherited.primitive_source,
        quantity=own.quantity or inherited.quantity,
        unit=own.unit or inherited.unit,
    )


def class_names(definitions: Sequence[Definition]) -> Dict[str, str]:
    """Map definition FQN → Python class name.

    A simple name declared by more than one definition is qualified with its
    owning path so that every generated class name is unique and stable.
    """
    by_name: Dict[str, List[Definition]] = {}
    for definition in definitions:
        by_name.setdefault(_identifier(definition.name), []).append(definition)

    names: Dict[str, str] = {}
    for simple, group in by_name.items():
        if len(group) == 1:
            names[group[0].id] = simple
            continue
        for definition in group:
            names[definition.id] = "_".join(
                _identifier(part) for part in definition.id.split("::")
            )
    return names


def _identifier(name: str) -> str:
    """Turn a SysML name into a Python identifier."""
    cleaned = "".join(char if char.isalnum() or char == "_" else "_" for char in name)
    if not cleaned or cleaned[0].isdigit():
        cleaned = "_" + cleaned
    if keyword.iskeyword(cleaned):
        cleaned += "_"
    return cleaned


def _literal(text: str) -> str:
    """Render a SysML name as a Python string literal, escaping quotes and backslashes."""
    return json.dumps(text, ensure_ascii=False)


def _docstring(text: str, indent: str) -> str:
    """Render a one-line docstring that cannot be terminated by the text it carries."""
    body = text.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    if body.endswith('"'):
        body = body[:-1] + '\\"'
    return f'{indent}"""{body}"""'


def property_name(name: str) -> str:
    """Python name of the property for a feature; the SysML feature name is unchanged."""
    identifier = _identifier(name)
    if identifier in RESERVED_MEMBERS:
        identifier += "_"
    return identifier


def element_type(type_facts: Optional[TypeFacts], names: Dict[str, str]) -> PythonType:
    """Map the type of a single value to a Python annotation and decoder."""
    if type_facts is None:
        return PythonType("object", _OBJECT_DECODER, "untyped feature")

    # A value written with a unit is a magnitude and that unit, whatever library
    # scalar the magnitude reduces to, so it is typed before the primitive below.
    if type_facts.quantity and type_facts.unit:
        return PythonType("_t.Quantity", "_t.as_quantity", f"quantity in [{type_facts.unit}]")
    if type_facts.quantity:
        # A quantity value type constrains the type, not what is written for it:
        # a plain number and a structured value both arrive here.
        return PythonType("object", _OBJECT_DECODER, "quantity value type, no unit written")

    # A definition reducing to a library scalar holds that scalar, not an
    # instance, even when it has a generated class of its own.
    primitive = type_facts.primitive
    if primitive in PRIMITIVE_TYPES:
        python = PRIMITIVE_TYPES[primitive]
        return PythonType(python, f"_t.as_{python}")

    # An enumeration-typed feature holds one of the enumeration's literals, which
    # is a value of its own rather than an instance of the generated class.
    if type_facts.resolved_kind == "enumDef":
        return PythonType("_t.EnumLiteral", "_t.as_enum_literal")

    if type_facts.resolved_id and type_facts.resolved_id in names:
        generated = names[type_facts.resolved_id]
        return PythonType(generated, f"_t.as_typed({generated})")

    if primitive in UNMAPPED_PRIMITIVES:
        return PythonType("object", _OBJECT_DECODER, f"SysML {primitive} has no Python counterpart")

    if type_facts.resolved_id:
        return PythonType(
            "object", _OBJECT_DECODER, f"SysML type {type_facts.resolved_id} has no generated class"
        )

    if type_facts.declared:
        return PythonType("object", _OBJECT_DECODER, f"unresolved SysML type {type_facts.declared}")

    return PythonType("object", _OBJECT_DECODER, "untyped feature")


def feature_type(feature: Feature, names: Dict[str, str]) -> PythonType:
    """Map a feature to its Python annotation, decoder and accessor, honoring multiplicity."""
    element = element_type(feature.facts.type, names)
    multiplicity = feature.facts.multiplicity or Multiplicity()

    if multiplicity.is_collection:
        return PythonType(f"list[{element.annotation}]", element.decoder, element.comment)
    if multiplicity.is_optional:
        return PythonType(f"{element.annotation} | None", element.decoder, element.comment)
    return element


def _accessor(feature: Feature) -> str:
    multiplicity = feature.facts.multiplicity or Multiplicity()
    if multiplicity.is_collection:
        return "_t.list_feature_value"
    if multiplicity.is_optional:
        return "_t.optional_feature_value"
    return "_t.feature_value"


def model_stamp(source_text: str) -> str:
    """Hash of the model source a generated module was produced from.

    Newlines are normalized so the same model checked out with CRLF endings
    stamps identically; nothing else about the text is interpreted.
    """
    normalized = source_text.replace("\r\n", "\n").replace("\r", "\n")
    digest = hashlib.new(MODEL_HASH_ALGORITHM, normalized.encode("utf-8"))
    return digest.hexdigest()


def _hash_literal(stamp: Optional[str]) -> str:
    """Value of the module's hash stamp, or the unstamped marker without one."""
    return f"{MODEL_HASH_ALGORITHM}:{stamp}" if stamp else UNSTAMPED


def render_module(
    definitions: Sequence[Definition], stamp: Optional[str] = None
) -> str:
    """Render a complete, importable Python module for ``definitions``.

    ``stamp`` is the :func:`model_stamp` of the model source, recorded in the
    module so a reader — and the ``--check`` gate — can tell what it was
    generated from. Without one the module says ``UNSTAMPED`` rather than
    claim a hash it does not have.
    """
    names = class_names(definitions)
    lines: List[str] = [
        GENERATED_HEADER,
        '"""Typed views over SysML definitions, generated from a parsed model."""',
        "",
        "from __future__ import annotations",
        "",
        "from opensysml import typed as _t",
        "",
        f"SYSML_GENERATOR_VERSION = {_literal(GENERATOR_VERSION)}",
        '"""Emission schema this module was generated with."""',
        "",
        f"SYSML_MODEL_HASH = {_literal(_hash_literal(stamp))}",
        '"""Hash of the model source this module was generated from."""',
    ]
    if not definitions:
        lines.append("")
        return "\n".join(lines)

    plan = _base_plan(definitions)
    for definition in _in_dependency_order(definitions):
        lines.extend(("", ""))
        lines.extend(_render_class(definition, names, plan[definition.id]))
    lines.append("")
    return "\n".join(lines)


def _base_plan(definitions: Sequence[Definition]) -> Dict[str, Tuple[Tuple[str, ...], ...]]:
    """Per definition: base FQNs kept as Python bases, and those dropped because
    Python could not linearize them.
    """
    generated = {definition.id for definition in definitions}
    linearizations: Dict[str, List[str]] = {}
    plan: Dict[str, Tuple[Tuple[str, ...], ...]] = {}

    for definition in _in_dependency_order(definitions):
        kept: List[str] = []
        declared = [
            base_id for base_id in dict.fromkeys(definition.base_ids)
            if base_id in generated
        ]
        candidates = [base_id for base_id in declared if base_id in linearizations]
        for base_id in _without_implied(candidates, linearizations):
            if _linearize(definition.id, kept + [base_id], linearizations) is None:
                continue
            kept.append(base_id)
        line = _linearize(definition.id, kept, linearizations) or [definition.id]
        linearizations[definition.id] = line
        # Anything the class does not end up inheriting, directly or through a kept
        # base, is reported rather than silently lost.
        dropped = [base_id for base_id in declared if base_id not in line]
        plan[definition.id] = (tuple(kept), tuple(dropped))
    return plan


def _without_implied(
    bases: Sequence[str], linearizations: Dict[str, List[str]]
) -> List[str]:
    """Drop each base another one already specializes, keeping declaration order.

    Naming both is what Python cannot linearize, and the more specific base
    carries the general one's members, so nothing is lost by leaving it out.
    """
    unique = list(dict.fromkeys(bases))
    return [
        base_id for base_id in unique
        if not any(
            base_id in linearizations[other][1:]
            for other in unique if other != base_id
        )
    ]


def _linearize(
    target: str, bases: Sequence[str], linearizations: Dict[str, List[str]]
) -> Optional[List[str]]:
    """C3 linearization of ``target`` over ``bases``, or None if there is none."""
    sequences = [list(linearizations[base]) for base in bases]
    sequences.append(list(bases))
    result = [target]
    while True:
        sequences = [sequence for sequence in sequences if sequence]
        if not sequences:
            return result
        for sequence in sequences:
            head = sequence[0]
            if not any(head in other[1:] for other in sequences):
                break
        else:
            return None
        result.append(head)
        for sequence in sequences:
            if sequence[0] == head:
                del sequence[0]


def _in_dependency_order(definitions: Sequence[Definition]) -> List[Definition]:
    """Order definitions so a base class is emitted before its subclasses.

    Ties and cycles keep FQN order, so emission stays deterministic.
    """
    by_id = {definition.id: definition for definition in definitions}
    ordered: List[Definition] = []
    emitted: set = set()
    visiting: set = set()

    def visit(definition: Definition) -> None:
        if definition.id in emitted or definition.id in visiting:
            return
        visiting.add(definition.id)
        for base_id in definition.base_ids:
            base = by_id.get(base_id)
            if base is not None:
                visit(base)
        visiting.discard(definition.id)
        emitted.add(definition.id)
        ordered.append(definition)

    for definition in definitions:
        visit(definition)
    return ordered


def _render_class(
    definition: Definition,
    names: Dict[str, str],
    plan: Optional[Tuple[Tuple[str, ...], ...]] = None,
) -> List[str]:
    kept, dropped = plan if plan is not None else (definition.base_ids, ())
    bases = [names[base_id] for base_id in kept if base_id in names]
    unmapped = [base_id for base_id in definition.base_ids if base_id not in names]
    edges = _edge_kinds(definition)
    header = f"class {names[definition.id]}({', '.join(bases) if bases else '_t.TypedObject'}):"

    lines = [header, _docstring(f"{definition.facts.kind} {definition.id}.", "    "), ""]
    notes = [
        f"    # {edges.get(base_id, 'specializes')} {base_id}, which has no generated class"
        for base_id in unmapped
    ] + [
        f"    # {edges.get(base_id, 'specializes')} {base_id}, left out: Python cannot "
        "linearize it with the bases above"
        for base_id in dropped
    ]
    for offset, note in enumerate(notes):
        lines.insert(2 + offset, note)
    lines.append(f"    sysml_id = {_literal(definition.id)}")

    for feature in definition.features:
        lines.append("")
        lines.extend(_render_property(feature, names))
    return lines


def _edge_kinds(definition: Definition) -> Dict[str, str]:
    """Map base FQN → the kind of generalization edge that named it."""
    return {
        spec.target_id: spec.kind
        for spec in definition.facts.specializations
        if spec.kind in GENERALIZATION_KINDS and spec.target_id
    }


def _render_property(feature: Feature, names: Dict[str, str]) -> List[str]:
    python_type = feature_type(feature, names)
    identifier = property_name(feature.name)
    lines = ["    @property", f"    def {identifier}(self) -> {python_type.annotation}:"]
    doc = f"{feature.facts.kind} {feature.facts.id}."
    if _identifier(feature.name) in RESERVED_MEMBERS:
        doc += f' Renamed from "{feature.name}", which TypedObject already defines.'
    if python_type.comment:
        doc += f" Mapped to {python_type.annotation}: {python_type.comment}."
    lines.append(_docstring(doc, "        "))
    lines.append(
        f"        return {_accessor(feature)}"
        f"(self, {_literal(feature.name)}, {python_type.decoder})"
    )
    return lines


def generate_source(model, source_text: str) -> str:
    """Render the typed module for a loaded :class:`~opensysml.model.Model`.

    ``source_text`` is the model source the module is stamped with; it is
    required so a module cannot silently claim the hash of nothing.
    """
    return render_module(collect_definitions(model.root), model_stamp(source_text))


# Named in the failure message below: which binary is at fault, and what to do.
TYPE_FACTS_REMEDY = (
    "install a sysml-grpc that reports the 'type_facts' capability. Build it from "
    "this repository with `make build-grpc` and run `bin/sysml-grpc`, or remove the "
    "cached binary at ~/.opensysml/bin/sysml-grpc and set $OPENSYSML_GRPC_VERSION to a "
    "release that has it. Generating against a service without type facts would emit "
    "a module in which every feature is typed `object`, indistinguishable from a "
    "feature that is genuinely untyped, so generation stops instead."
)


def require_type_facts(connection) -> None:
    """Fail unless ``connection``'s service can supply static type facts.

    Raises:
        MissingCapabilityError: If the service does not report the capability,
            including when it is too old to answer the handshake at all.
    """
    require(connection.server_info(), CAPABILITY_TYPE_FACTS, TYPE_FACTS_REMEDY)


def main(argv: Optional[Iterable[str]] = None) -> int:
    """Entry point for ``python -m opensysml.generate``."""
    parser = argparse.ArgumentParser(
        prog="python -m opensysml.generate",
        description="Generate typed Python classes from a SysML model.",
    )
    parser.add_argument("source", help="path to a .sysml file")
    parser.add_argument("-o", "--output", help="output .py path (default: stdout)")
    parser.add_argument("--host", default="localhost", help="sysml-grpc host")
    # No default: an unwritten port lets --host carry its own (default 50051).
    parser.add_argument("--port", type=int, help="sysml-grpc port (default: 50051)")
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit non-zero if regenerating would change --output",
    )
    args = parser.parse_args(list(argv) if argv is not None else None)

    # Imported here, not at module scope: opensysml's init imports this module.
    import opensysml

    if args.check and not args.output:
        print("error: --check requires -o/--output", file=sys.stderr)
        return 2

    try:
        with open(args.source, encoding="utf-8") as handle:
            source_text = handle.read()
    except OSError as exc:
        print(f"error: cannot read {args.source}: {exc}", file=sys.stderr)
        return 2

    try:
        connection = opensysml.connect(args.host, args.port)
    except ValueError as exc:
        # A misread --host/--port is the caller's mistake, not a crash.
        print(f"error: {exc}", file=sys.stderr)
        return 2

    # A connection of this run's own, closed when the run ends.
    with connection:
        model = connection.load(args.source)

        try:
            require_type_facts(connection)
        except MissingCapabilityError as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 1

        errors = [diag for diag in model.diagnostics if diag.severity == "error"]
        if errors:
            for diag in errors:
                print(f"error: {diag.message}", file=sys.stderr)
            return 1

        source = generate_source(model, source_text)

    if args.check:
        existing = None
        if os.path.exists(args.output):
            with open(args.output, encoding="utf-8") as handle:
                existing = handle.read()
        if existing == source:
            return 0
        reason = "does not exist" if existing is None else "is out of date"
        print(
            f"error: {args.output} {reason}; regenerate with: "
            f"python -m opensysml.generate {args.source} -o {args.output}",
            file=sys.stderr,
        )
        return 1

    if args.output:
        with open(args.output, "w", encoding="utf-8") as handle:
            handle.write(source)
    else:
        sys.stdout.write(source)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
