package solve

// Randomized differential testing generates models rather than assignments: the
// evaluator reads the values a model declares, so a generated assignment is a
// generated model, and both layers then answer about the same values without any
// AST being mutated. The generated values cover boundaries, negative numbers,
// zero divisors, mixed signs, enumeration literals, selected variants and
// quantities in non-base units.
//
// The default seed is fixed, so a failure reproduces exactly; rerun it with
// OPENSYSML_DIFF_SEED=<seed>, which the report names. The default run generates
// one document, which keeps it fast; OPENSYSML_DIFF_SWEEP=<documents> runs a
// longer sweep from consecutive seeds, and -short keeps the sweep off.

import (
	"fmt"
	"math/rand"
	"os"
	"strconv"
	"strings"
	"testing"
)

const (
	// diffSeedEnv overrides the fixed default seed, reproducing a failure.
	diffSeedEnv = "OPENSYSML_DIFF_SEED"

	// diffSweepEnv asks for more generated documents than the default run.
	diffSweepEnv = "OPENSYSML_DIFF_SWEEP"

	// diffDefaultSeed keeps the default run deterministic.
	diffDefaultSeed = 1

	// diffCasesPerDocument is how many generated constraints share one parse of
	// the standard library, which dominates the cost of a document.
	diffCasesPerDocument = 24
)

// TestDifferentialRandomizedAssignments generates models over the translatable
// subset and requires the evaluator and the solver to agree about each of them.
func TestDifferentialRandomizedAssignments(t *testing.T) {
	gate := newGate(t, "randomized assignments")
	seed := diffSeed(t)
	documents := diffDocuments(t)

	for i := 0; i < documents; i++ {
		docSeed := seed + int64(i)
		src := generateModel(docSeed)
		path := fmt.Sprintf("generated-seed-%d.sysml", docSeed)
		gate.summary.files++
		t.Run(strconv.FormatInt(docSeed, 10), func(t *testing.T) {
			ctx, idx := modelOf(t, path, []byte(src), true)
			elements := conditionElements(ctx, idx, path)
			if len(elements) != diffCasesPerDocument {
				t.Fatalf("the generator emitted %d constraints the gate can see, want %d:\n%s",
					len(elements), diffCasesPerDocument, src)
			}
			disagreed := false
			for _, el := range elements {
				disagreed = gate.check(t, ctx, el) == diffDisagreed || disagreed
			}
			if disagreed {
				t.Logf("reproduce with %s=%d; generated model:\n%s", diffSeedEnv, docSeed, src)
			}
		})
	}

	gate.summary.report(t)
	t.Logf("differential gate randomized assignments: seed %d, %d document(s) of %d constraints "+
		"(rerun with %s=%d, sweep with %s=<documents>)",
		seed, documents, diffCasesPerDocument, diffSeedEnv, seed, diffSweepEnv)
	if gate.summary.counts[diffAgreed] == 0 {
		t.Errorf("the gate agreed on nothing, so it checked nothing: %+v", gate.summary.counts)
	}
}

// diffSeed is the seed the run generates from: the fixed default, or the one an
// environment variable reproduces a failure with.
func diffSeed(t *testing.T) int64 {
	t.Helper()
	text := os.Getenv(diffSeedEnv)
	if text == "" {
		return diffDefaultSeed
	}
	seed, err := strconv.ParseInt(text, 10, 64)
	if err != nil {
		t.Fatalf("%s=%s is not a seed: %v", diffSeedEnv, text, err)
	}
	return seed
}

// diffDocuments is how many documents the run generates: one by default, more
// for an explicitly asked-for sweep, which -short declines.
func diffDocuments(t *testing.T) int {
	t.Helper()
	text := os.Getenv(diffSweepEnv)
	if text == "" {
		return 1
	}
	documents, err := strconv.Atoi(text)
	if err != nil || documents < 1 {
		t.Fatalf("%s=%s is not a number of documents", diffSweepEnv, text)
	}
	if testing.Short() && documents > 1 {
		t.Logf("-short declines the %s=%d sweep, generating one document", diffSweepEnv, documents)
		return 1
	}
	return documents
}

// generateModel emits one document: a definition of the features the generated
// conditions read, a variation family they select a variant of, and one part per
// case declaring that case's values and asserting its generated condition.
func generateModel(seed int64) string {
	rng := rand.New(rand.NewSource(seed))
	var b strings.Builder
	b.WriteString(`// Generated by TestDifferentialRandomizedAssignments; not a fixture.
package gen {
	private import ScalarValues::*;
	private import SI::*;
	private import ISQSpaceTime::*;

	enum def Color { red; green; blue; }

	attribute def Shape { attribute cost : Real; }

	part def Case {
		attribute a : Real;
		attribute b : Real;
		attribute i : Integer;
		attribute j : Integer;
		attribute p : Boolean;
		attribute q : Boolean;
		attribute label : String;
		attribute c : Color;
		attribute shape : Shape;
		attribute v : ISQSpaceTime::SpeedValue;
		attribute w : ISQSpaceTime::SpeedValue;
	}

	abstract part family : Case {
		variation attribute :>> shape {
			variant attribute round { :>> cost = 10.0; }
			variant attribute square { :>> cost = -2.5; }
		}
	}
`)
	for i := 0; i < diffCasesPerDocument; i++ {
		g := &generator{rng: rng}
		fmt.Fprintf(&b, "\n\tpart case%d :> family {\n", i)
		fmt.Fprintf(&b, "\t\tattribute :>> a = %s;\n", g.real())
		fmt.Fprintf(&b, "\t\tattribute :>> b = %s;\n", g.real())
		fmt.Fprintf(&b, "\t\tattribute :>> i = %s;\n", g.integer())
		fmt.Fprintf(&b, "\t\tattribute :>> j = %s;\n", g.integer())
		fmt.Fprintf(&b, "\t\tattribute :>> p = %s;\n", g.boolean())
		fmt.Fprintf(&b, "\t\tattribute :>> q = %s;\n", g.boolean())
		fmt.Fprintf(&b, "\t\tattribute :>> label = %s;\n", g.text())
		fmt.Fprintf(&b, "\t\tattribute :>> c = Color::%s;\n", g.color())
		fmt.Fprintf(&b, "\t\tattribute :>> shape = shape::%s;\n", g.variant())
		fmt.Fprintf(&b, "\t\tattribute :>> v = %s [km/h];\n", g.real())
		fmt.Fprintf(&b, "\t\tattribute :>> w = %s [m/s];\n", g.real())
		negated := ""
		if g.chance(4) {
			negated = "not "
		}
		fmt.Fprintf(&b, "\n\t\tassert %sconstraint k%d {\n\t\t\t%s\n\t\t}\n\t}\n",
			negated, i, g.condition(3))
	}
	b.WriteString("}\n")
	return b.String()
}

// generator draws the values and the condition of one generated case.
type generator struct{ rng *rand.Rand }

// chance reports true one time in n.
func (g *generator) chance(n int) bool { return g.rng.Intn(n) == 0 }

// pick chooses one of the given alternatives.
func (g *generator) pick(options ...string) string { return options[g.rng.Intn(len(options))] }

// real draws a real value, including zero, negatives and magnitudes far apart,
// written as a literal the translation reads exactly.
func (g *generator) real() string {
	return g.pick("0.0", "1.0", "-1.0", "0.5", "-0.5", "2.0", "-3.25", "10.0",
		"-10.0", "0.1", "36.0", "-100.0", "1000000.0", "0.000001")
}

// integer draws an integer value, including zero divisors and mixed signs.
func (g *generator) integer() string {
	return g.pick("0", "1", "-1", "2", "-2", "3", "-7", "10", "-10", "1000000", "-1000000")
}

func (g *generator) boolean() string { return g.pick("true", "false") }
func (g *generator) text() string    { return g.pick(`""`, `"x"`, `"abc"`, `"ABC"`) }
func (g *generator) color() string   { return g.pick("red", "green", "blue") }
func (g *generator) variant() string { return g.pick("round", "square") }

// condition draws a boolean condition of at most the given depth. A division is
// drawn at the top level, where the translation may guard its divisor, so a zero
// divisor exercises the evaluator's refusal against that guard.
func (g *generator) condition(depth int) string {
	if g.chance(3) {
		return g.pick(
			"a / b "+g.comparison()+" "+g.real(),
			"i / j "+g.comparison()+" "+g.integer(),
			"i % j "+g.comparison()+" "+g.integer(),
		)
	}
	return g.boolExpr(depth)
}

// boolExpr draws a boolean expression of at most the given depth.
func (g *generator) boolExpr(depth int) string {
	if depth <= 0 {
		return g.atom()
	}
	switch g.rng.Intn(8) {
	case 0:
		return "not (" + g.boolExpr(depth-1) + ")"
	case 1, 2:
		return "(" + g.boolExpr(depth-1) + ") " +
			g.pick("and", "or", "xor", "implies", "==", "!=") + " (" + g.boolExpr(depth-1) + ")"
	case 3:
		return "(if " + g.atom() + " ? " + g.boolExpr(depth-1) + " else " + g.boolExpr(depth-1) + ")"
	default:
		return g.atom()
	}
}

// atom draws a boolean expression over the generated features: a numeric
// comparison, a quantity comparison across units, an enumeration or variant
// equality, a string equality, or a boolean feature.
func (g *generator) atom() string {
	switch g.rng.Intn(7) {
	case 0:
		return g.pick("p", "q", "not p", "not q")
	case 1:
		return g.realExpr(2) + " " + g.comparison() + " " + g.realExpr(1)
	case 2:
		return g.intExpr(2) + " " + g.comparison() + " " + g.intExpr(1)
	case 3:
		return "v " + g.comparison() + " w"
	case 4:
		return "c " + g.pick("==", "!=") + " Color::" + g.color()
	case 5:
		return "label " + g.pick("==", "!=") + " " + g.text()
	default:
		return "shape " + g.pick("==", "!=") + " shape::" + g.variant()
	}
}

// comparison draws a comparison operator.
func (g *generator) comparison() string {
	return g.pick("<", "<=", ">", ">=", "==", "!=")
}

// realExpr draws a real-valued expression. Division is left to the top level,
// where a guarded divisor means what the evaluator means.
func (g *generator) realExpr(depth int) string {
	if depth <= 0 {
		return g.pick("a", "b", "shape.cost", g.real())
	}
	switch g.rng.Intn(5) {
	case 0:
		return "(" + g.realExpr(depth-1) + " " + g.pick("+", "-", "*") + " " + g.realExpr(depth-1) + ")"
	case 1:
		return "(0 - " + g.realExpr(depth-1) + ")"
	default:
		return g.realExpr(0)
	}
}

// intExpr draws an integer-valued expression, leaving division and remainder to
// the top level for the same reason as realExpr.
func (g *generator) intExpr(depth int) string {
	if depth <= 0 {
		return g.pick("i", "j", g.integer())
	}
	switch g.rng.Intn(5) {
	case 0:
		return "(" + g.intExpr(depth-1) + " " + g.pick("+", "-", "*") + " " + g.intExpr(depth-1) + ")"
	case 1:
		return "(0 - " + g.intExpr(depth-1) + ")"
	default:
		return g.intExpr(0)
	}
}
