// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package org.openmbee.opensysml.proto;

/**
 * <pre>
 * AddSequenceEdit inserts a `first` or `then` sequencing member into an action body.
 * </pre>
 *
 * Protobuf type {@code sysml.AddSequenceEdit}
 */
@com.google.protobuf.Generated
public final class AddSequenceEdit extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:sysml.AddSequenceEdit)
    AddSequenceEditOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "AddSequenceEdit");
  }
  // Use AddSequenceEdit.newBuilder() to construct.
  private AddSequenceEdit(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AddSequenceEdit() {
    owner_ = "";
    keyword_ = "";
    ref_ = "";
    memberKind_ = "";
    memberName_ = "";
    type_ = "";
    after_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_AddSequenceEdit_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_AddSequenceEdit_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.openmbee.opensysml.proto.AddSequenceEdit.class, org.openmbee.opensysml.proto.AddSequenceEdit.Builder.class);
  }

  public static final int OWNER_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object owner_ = "";
  /**
   * <pre>
   * Action body receiving the member.
   * </pre>
   *
   * <code>string owner = 1 [json_name = "owner"];</code>
   * @return The owner.
   */
  @java.lang.Override
  public java.lang.String getOwner() {
    java.lang.Object ref = owner_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      owner_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Action body receiving the member.
   * </pre>
   *
   * <code>string owner = 1 [json_name = "owner"];</code>
   * @return The bytes for owner.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOwnerBytes() {
    java.lang.Object ref = owner_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      owner_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KEYWORD_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object keyword_ = "";
  /**
   * <pre>
   * Sequence keyword: "first" or "then".
   * </pre>
   *
   * <code>string keyword = 2 [json_name = "keyword"];</code>
   * @return The keyword.
   */
  @java.lang.Override
  public java.lang.String getKeyword() {
    java.lang.Object ref = keyword_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      keyword_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Sequence keyword: "first" or "then".
   * </pre>
   *
   * <code>string keyword = 2 [json_name = "keyword"];</code>
   * @return The bytes for keyword.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKeywordBytes() {
    java.lang.Object ref = keyword_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      keyword_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REF_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object ref_ = "";
  /**
   * <pre>
   * Node a bare `first &lt;ref&gt;;`/`then &lt;ref&gt;;` names; empty when the `then`
   * declares a member instead.
   * </pre>
   *
   * <code>string ref = 3 [json_name = "ref"];</code>
   * @return The ref.
   */
  @java.lang.Override
  public java.lang.String getRef() {
    java.lang.Object ref = ref_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ref_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Node a bare `first &lt;ref&gt;;`/`then &lt;ref&gt;;` names; empty when the `then`
   * declares a member instead.
   * </pre>
   *
   * <code>string ref = 3 [json_name = "ref"];</code>
   * @return The bytes for ref.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRefBytes() {
    java.lang.Object ref = ref_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ref_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MEMBER_KIND_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object memberKind_ = "";
  /**
   * <pre>
   * Usage kind a `then` declares: action, perform action, state, merge,
   * decide, join or fork; empty when ref names the target.
   * </pre>
   *
   * <code>string member_kind = 4 [json_name = "memberKind"];</code>
   * @return The memberKind.
   */
  @java.lang.Override
  public java.lang.String getMemberKind() {
    java.lang.Object ref = memberKind_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      memberKind_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Usage kind a `then` declares: action, perform action, state, merge,
   * decide, join or fork; empty when ref names the target.
   * </pre>
   *
   * <code>string member_kind = 4 [json_name = "memberKind"];</code>
   * @return The bytes for memberKind.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMemberKindBytes() {
    java.lang.Object ref = memberKind_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      memberKind_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MEMBER_NAME_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object memberName_ = "";
  /**
   * <pre>
   * Optional declared name of the `then`-declared member.
   * </pre>
   *
   * <code>string member_name = 5 [json_name = "memberName"];</code>
   * @return The memberName.
   */
  @java.lang.Override
  public java.lang.String getMemberName() {
    java.lang.Object ref = memberName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      memberName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional declared name of the `then`-declared member.
   * </pre>
   *
   * <code>string member_name = 5 [json_name = "memberName"];</code>
   * @return The bytes for memberName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMemberNameBytes() {
    java.lang.Object ref = memberName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      memberName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object type_ = "";
  /**
   * <pre>
   * Optional typing target of the `then`-declared member.
   * </pre>
   *
   * <code>string type = 6 [json_name = "type"];</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional typing target of the `then`-declared member.
   * </pre>
   *
   * <code>string type = 6 [json_name = "type"];</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AFTER_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object after_ = "";
  /**
   * <pre>
   * Optional name of the body member the new member follows.
   * </pre>
   *
   * <code>string after = 7 [json_name = "after"];</code>
   * @return The after.
   */
  @java.lang.Override
  public java.lang.String getAfter() {
    java.lang.Object ref = after_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      after_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional name of the body member the new member follows.
   * </pre>
   *
   * <code>string after = 7 [json_name = "after"];</code>
   * @return The bytes for after.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAfterBytes() {
    java.lang.Object ref = after_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      after_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(owner_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, owner_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(keyword_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, keyword_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ref_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, ref_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(memberKind_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, memberKind_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(memberName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, memberName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(type_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, type_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(after_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, after_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(owner_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, owner_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(keyword_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, keyword_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ref_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, ref_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(memberKind_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, memberKind_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(memberName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, memberName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(type_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, type_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(after_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, after_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.openmbee.opensysml.proto.AddSequenceEdit)) {
      return super.equals(obj);
    }
    org.openmbee.opensysml.proto.AddSequenceEdit other = (org.openmbee.opensysml.proto.AddSequenceEdit) obj;

    if (!getOwner()
        .equals(other.getOwner())) return false;
    if (!getKeyword()
        .equals(other.getKeyword())) return false;
    if (!getRef()
        .equals(other.getRef())) return false;
    if (!getMemberKind()
        .equals(other.getMemberKind())) return false;
    if (!getMemberName()
        .equals(other.getMemberName())) return false;
    if (!getType()
        .equals(other.getType())) return false;
    if (!getAfter()
        .equals(other.getAfter())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OWNER_FIELD_NUMBER;
    hash = (53 * hash) + getOwner().hashCode();
    hash = (37 * hash) + KEYWORD_FIELD_NUMBER;
    hash = (53 * hash) + getKeyword().hashCode();
    hash = (37 * hash) + REF_FIELD_NUMBER;
    hash = (53 * hash) + getRef().hashCode();
    hash = (37 * hash) + MEMBER_KIND_FIELD_NUMBER;
    hash = (53 * hash) + getMemberKind().hashCode();
    hash = (37 * hash) + MEMBER_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getMemberName().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (37 * hash) + AFTER_FIELD_NUMBER;
    hash = (53 * hash) + getAfter().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.openmbee.opensysml.proto.AddSequenceEdit parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmbee.opensysml.proto.AddSequenceEdit parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.AddSequenceEdit parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmbee.opensysml.proto.AddSequenceEdit parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.AddSequenceEdit parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmbee.opensysml.proto.AddSequenceEdit parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.AddSequenceEdit parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.openmbee.opensysml.proto.AddSequenceEdit parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.openmbee.opensysml.proto.AddSequenceEdit parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.openmbee.opensysml.proto.AddSequenceEdit parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.AddSequenceEdit parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.openmbee.opensysml.proto.AddSequenceEdit parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.openmbee.opensysml.proto.AddSequenceEdit prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * AddSequenceEdit inserts a `first` or `then` sequencing member into an action body.
   * </pre>
   *
   * Protobuf type {@code sysml.AddSequenceEdit}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sysml.AddSequenceEdit)
      org.openmbee.opensysml.proto.AddSequenceEditOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_AddSequenceEdit_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_AddSequenceEdit_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.openmbee.opensysml.proto.AddSequenceEdit.class, org.openmbee.opensysml.proto.AddSequenceEdit.Builder.class);
    }

    // Construct using org.openmbee.opensysml.proto.AddSequenceEdit.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      owner_ = "";
      keyword_ = "";
      ref_ = "";
      memberKind_ = "";
      memberName_ = "";
      type_ = "";
      after_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_AddSequenceEdit_descriptor;
    }

    @java.lang.Override
    public org.openmbee.opensysml.proto.AddSequenceEdit getDefaultInstanceForType() {
      return org.openmbee.opensysml.proto.AddSequenceEdit.getDefaultInstance();
    }

    @java.lang.Override
    public org.openmbee.opensysml.proto.AddSequenceEdit build() {
      org.openmbee.opensysml.proto.AddSequenceEdit result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.openmbee.opensysml.proto.AddSequenceEdit buildPartial() {
      org.openmbee.opensysml.proto.AddSequenceEdit result = new org.openmbee.opensysml.proto.AddSequenceEdit(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.openmbee.opensysml.proto.AddSequenceEdit result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.owner_ = owner_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.keyword_ = keyword_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.ref_ = ref_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.memberKind_ = memberKind_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.memberName_ = memberName_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.after_ = after_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.openmbee.opensysml.proto.AddSequenceEdit) {
        return mergeFrom((org.openmbee.opensysml.proto.AddSequenceEdit)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.openmbee.opensysml.proto.AddSequenceEdit other) {
      if (other == org.openmbee.opensysml.proto.AddSequenceEdit.getDefaultInstance()) return this;
      if (!other.getOwner().isEmpty()) {
        owner_ = other.owner_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getKeyword().isEmpty()) {
        keyword_ = other.keyword_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getRef().isEmpty()) {
        ref_ = other.ref_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getMemberKind().isEmpty()) {
        memberKind_ = other.memberKind_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getMemberName().isEmpty()) {
        memberName_ = other.memberName_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getAfter().isEmpty()) {
        after_ = other.after_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              owner_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              keyword_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              ref_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              memberKind_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              memberName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              type_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              after_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object owner_ = "";
    /**
     * <pre>
     * Action body receiving the member.
     * </pre>
     *
     * <code>string owner = 1 [json_name = "owner"];</code>
     * @return The owner.
     */
    public java.lang.String getOwner() {
      java.lang.Object ref = owner_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        owner_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Action body receiving the member.
     * </pre>
     *
     * <code>string owner = 1 [json_name = "owner"];</code>
     * @return The bytes for owner.
     */
    public com.google.protobuf.ByteString
        getOwnerBytes() {
      java.lang.Object ref = owner_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        owner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Action body receiving the member.
     * </pre>
     *
     * <code>string owner = 1 [json_name = "owner"];</code>
     * @param value The owner to set.
     * @return This builder for chaining.
     */
    public Builder setOwner(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      owner_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Action body receiving the member.
     * </pre>
     *
     * <code>string owner = 1 [json_name = "owner"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOwner() {
      owner_ = getDefaultInstance().getOwner();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Action body receiving the member.
     * </pre>
     *
     * <code>string owner = 1 [json_name = "owner"];</code>
     * @param value The bytes for owner to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      owner_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object keyword_ = "";
    /**
     * <pre>
     * Sequence keyword: "first" or "then".
     * </pre>
     *
     * <code>string keyword = 2 [json_name = "keyword"];</code>
     * @return The keyword.
     */
    public java.lang.String getKeyword() {
      java.lang.Object ref = keyword_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        keyword_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Sequence keyword: "first" or "then".
     * </pre>
     *
     * <code>string keyword = 2 [json_name = "keyword"];</code>
     * @return The bytes for keyword.
     */
    public com.google.protobuf.ByteString
        getKeywordBytes() {
      java.lang.Object ref = keyword_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        keyword_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Sequence keyword: "first" or "then".
     * </pre>
     *
     * <code>string keyword = 2 [json_name = "keyword"];</code>
     * @param value The keyword to set.
     * @return This builder for chaining.
     */
    public Builder setKeyword(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      keyword_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Sequence keyword: "first" or "then".
     * </pre>
     *
     * <code>string keyword = 2 [json_name = "keyword"];</code>
     * @return This builder for chaining.
     */
    public Builder clearKeyword() {
      keyword_ = getDefaultInstance().getKeyword();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Sequence keyword: "first" or "then".
     * </pre>
     *
     * <code>string keyword = 2 [json_name = "keyword"];</code>
     * @param value The bytes for keyword to set.
     * @return This builder for chaining.
     */
    public Builder setKeywordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      keyword_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object ref_ = "";
    /**
     * <pre>
     * Node a bare `first &lt;ref&gt;;`/`then &lt;ref&gt;;` names; empty when the `then`
     * declares a member instead.
     * </pre>
     *
     * <code>string ref = 3 [json_name = "ref"];</code>
     * @return The ref.
     */
    public java.lang.String getRef() {
      java.lang.Object ref = ref_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ref_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Node a bare `first &lt;ref&gt;;`/`then &lt;ref&gt;;` names; empty when the `then`
     * declares a member instead.
     * </pre>
     *
     * <code>string ref = 3 [json_name = "ref"];</code>
     * @return The bytes for ref.
     */
    public com.google.protobuf.ByteString
        getRefBytes() {
      java.lang.Object ref = ref_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ref_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Node a bare `first &lt;ref&gt;;`/`then &lt;ref&gt;;` names; empty when the `then`
     * declares a member instead.
     * </pre>
     *
     * <code>string ref = 3 [json_name = "ref"];</code>
     * @param value The ref to set.
     * @return This builder for chaining.
     */
    public Builder setRef(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ref_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Node a bare `first &lt;ref&gt;;`/`then &lt;ref&gt;;` names; empty when the `then`
     * declares a member instead.
     * </pre>
     *
     * <code>string ref = 3 [json_name = "ref"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRef() {
      ref_ = getDefaultInstance().getRef();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Node a bare `first &lt;ref&gt;;`/`then &lt;ref&gt;;` names; empty when the `then`
     * declares a member instead.
     * </pre>
     *
     * <code>string ref = 3 [json_name = "ref"];</code>
     * @param value The bytes for ref to set.
     * @return This builder for chaining.
     */
    public Builder setRefBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ref_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object memberKind_ = "";
    /**
     * <pre>
     * Usage kind a `then` declares: action, perform action, state, merge,
     * decide, join or fork; empty when ref names the target.
     * </pre>
     *
     * <code>string member_kind = 4 [json_name = "memberKind"];</code>
     * @return The memberKind.
     */
    public java.lang.String getMemberKind() {
      java.lang.Object ref = memberKind_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        memberKind_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Usage kind a `then` declares: action, perform action, state, merge,
     * decide, join or fork; empty when ref names the target.
     * </pre>
     *
     * <code>string member_kind = 4 [json_name = "memberKind"];</code>
     * @return The bytes for memberKind.
     */
    public com.google.protobuf.ByteString
        getMemberKindBytes() {
      java.lang.Object ref = memberKind_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        memberKind_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Usage kind a `then` declares: action, perform action, state, merge,
     * decide, join or fork; empty when ref names the target.
     * </pre>
     *
     * <code>string member_kind = 4 [json_name = "memberKind"];</code>
     * @param value The memberKind to set.
     * @return This builder for chaining.
     */
    public Builder setMemberKind(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      memberKind_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Usage kind a `then` declares: action, perform action, state, merge,
     * decide, join or fork; empty when ref names the target.
     * </pre>
     *
     * <code>string member_kind = 4 [json_name = "memberKind"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMemberKind() {
      memberKind_ = getDefaultInstance().getMemberKind();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Usage kind a `then` declares: action, perform action, state, merge,
     * decide, join or fork; empty when ref names the target.
     * </pre>
     *
     * <code>string member_kind = 4 [json_name = "memberKind"];</code>
     * @param value The bytes for memberKind to set.
     * @return This builder for chaining.
     */
    public Builder setMemberKindBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      memberKind_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object memberName_ = "";
    /**
     * <pre>
     * Optional declared name of the `then`-declared member.
     * </pre>
     *
     * <code>string member_name = 5 [json_name = "memberName"];</code>
     * @return The memberName.
     */
    public java.lang.String getMemberName() {
      java.lang.Object ref = memberName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        memberName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional declared name of the `then`-declared member.
     * </pre>
     *
     * <code>string member_name = 5 [json_name = "memberName"];</code>
     * @return The bytes for memberName.
     */
    public com.google.protobuf.ByteString
        getMemberNameBytes() {
      java.lang.Object ref = memberName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        memberName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional declared name of the `then`-declared member.
     * </pre>
     *
     * <code>string member_name = 5 [json_name = "memberName"];</code>
     * @param value The memberName to set.
     * @return This builder for chaining.
     */
    public Builder setMemberName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      memberName_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional declared name of the `then`-declared member.
     * </pre>
     *
     * <code>string member_name = 5 [json_name = "memberName"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMemberName() {
      memberName_ = getDefaultInstance().getMemberName();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional declared name of the `then`-declared member.
     * </pre>
     *
     * <code>string member_name = 5 [json_name = "memberName"];</code>
     * @param value The bytes for memberName to set.
     * @return This builder for chaining.
     */
    public Builder setMemberNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      memberName_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <pre>
     * Optional typing target of the `then`-declared member.
     * </pre>
     *
     * <code>string type = 6 [json_name = "type"];</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional typing target of the `then`-declared member.
     * </pre>
     *
     * <code>string type = 6 [json_name = "type"];</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional typing target of the `then`-declared member.
     * </pre>
     *
     * <code>string type = 6 [json_name = "type"];</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      type_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional typing target of the `then`-declared member.
     * </pre>
     *
     * <code>string type = 6 [json_name = "type"];</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      type_ = getDefaultInstance().getType();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional typing target of the `then`-declared member.
     * </pre>
     *
     * <code>string type = 6 [json_name = "type"];</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      type_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object after_ = "";
    /**
     * <pre>
     * Optional name of the body member the new member follows.
     * </pre>
     *
     * <code>string after = 7 [json_name = "after"];</code>
     * @return The after.
     */
    public java.lang.String getAfter() {
      java.lang.Object ref = after_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        after_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional name of the body member the new member follows.
     * </pre>
     *
     * <code>string after = 7 [json_name = "after"];</code>
     * @return The bytes for after.
     */
    public com.google.protobuf.ByteString
        getAfterBytes() {
      java.lang.Object ref = after_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        after_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional name of the body member the new member follows.
     * </pre>
     *
     * <code>string after = 7 [json_name = "after"];</code>
     * @param value The after to set.
     * @return This builder for chaining.
     */
    public Builder setAfter(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      after_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional name of the body member the new member follows.
     * </pre>
     *
     * <code>string after = 7 [json_name = "after"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAfter() {
      after_ = getDefaultInstance().getAfter();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional name of the body member the new member follows.
     * </pre>
     *
     * <code>string after = 7 [json_name = "after"];</code>
     * @param value The bytes for after to set.
     * @return This builder for chaining.
     */
    public Builder setAfterBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      after_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sysml.AddSequenceEdit)
  }

  // @@protoc_insertion_point(class_scope:sysml.AddSequenceEdit)
  private static final org.openmbee.opensysml.proto.AddSequenceEdit DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.openmbee.opensysml.proto.AddSequenceEdit();
  }

  public static org.openmbee.opensysml.proto.AddSequenceEdit getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddSequenceEdit>
      PARSER = new com.google.protobuf.AbstractParser<AddSequenceEdit>() {
    @java.lang.Override
    public AddSequenceEdit parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AddSequenceEdit> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AddSequenceEdit> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.openmbee.opensysml.proto.AddSequenceEdit getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

