// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package org.openmbee.opensysml.proto;

/**
 * <pre>
 * DocumentQueryRow is one selected element and its projected cells, one per
 * column in column order.
 * </pre>
 *
 * Protobuf type {@code sysml.DocumentQueryRow}
 */
@com.google.protobuf.Generated
public final class DocumentQueryRow extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:sysml.DocumentQueryRow)
    DocumentQueryRowOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "DocumentQueryRow");
  }
  // Use DocumentQueryRow.newBuilder() to construct.
  private DocumentQueryRow(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private DocumentQueryRow() {
    cells_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_DocumentQueryRow_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_DocumentQueryRow_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.openmbee.opensysml.proto.DocumentQueryRow.class, org.openmbee.opensysml.proto.DocumentQueryRow.Builder.class);
  }

  private int bitField0_;
  public static final int ELEMENT_FIELD_NUMBER = 1;
  private org.openmbee.opensysml.proto.DocumentValue element_;
  /**
   * <pre>
   * The selected element itself, an element value with its qualified name; an
   * object value for a row over an object the service holds; a verdict value
   * for a row `Verdicts` answered; a state value for a row `States` answered;
   * an event value for a row `Events` answered.
   * </pre>
   *
   * <code>.sysml.DocumentValue element = 1 [json_name = "element"];</code>
   * @return Whether the element field is set.
   */
  @java.lang.Override
  public boolean hasElement() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * The selected element itself, an element value with its qualified name; an
   * object value for a row over an object the service holds; a verdict value
   * for a row `Verdicts` answered; a state value for a row `States` answered;
   * an event value for a row `Events` answered.
   * </pre>
   *
   * <code>.sysml.DocumentValue element = 1 [json_name = "element"];</code>
   * @return The element.
   */
  @java.lang.Override
  public org.openmbee.opensysml.proto.DocumentValue getElement() {
    return element_ == null ? org.openmbee.opensysml.proto.DocumentValue.getDefaultInstance() : element_;
  }
  /**
   * <pre>
   * The selected element itself, an element value with its qualified name; an
   * object value for a row over an object the service holds; a verdict value
   * for a row `Verdicts` answered; a state value for a row `States` answered;
   * an event value for a row `Events` answered.
   * </pre>
   *
   * <code>.sysml.DocumentValue element = 1 [json_name = "element"];</code>
   */
  @java.lang.Override
  public org.openmbee.opensysml.proto.DocumentValueOrBuilder getElementOrBuilder() {
    return element_ == null ? org.openmbee.opensysml.proto.DocumentValue.getDefaultInstance() : element_;
  }

  public static final int CELLS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<org.openmbee.opensysml.proto.DocumentQueryCell> cells_;
  /**
   * <code>repeated .sysml.DocumentQueryCell cells = 2 [json_name = "cells"];</code>
   */
  @java.lang.Override
  public java.util.List<org.openmbee.opensysml.proto.DocumentQueryCell> getCellsList() {
    return cells_;
  }
  /**
   * <code>repeated .sysml.DocumentQueryCell cells = 2 [json_name = "cells"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.openmbee.opensysml.proto.DocumentQueryCellOrBuilder> 
      getCellsOrBuilderList() {
    return cells_;
  }
  /**
   * <code>repeated .sysml.DocumentQueryCell cells = 2 [json_name = "cells"];</code>
   */
  @java.lang.Override
  public int getCellsCount() {
    return cells_.size();
  }
  /**
   * <code>repeated .sysml.DocumentQueryCell cells = 2 [json_name = "cells"];</code>
   */
  @java.lang.Override
  public org.openmbee.opensysml.proto.DocumentQueryCell getCells(int index) {
    return cells_.get(index);
  }
  /**
   * <code>repeated .sysml.DocumentQueryCell cells = 2 [json_name = "cells"];</code>
   */
  @java.lang.Override
  public org.openmbee.opensysml.proto.DocumentQueryCellOrBuilder getCellsOrBuilder(
      int index) {
    return cells_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getElement());
    }
    for (int i = 0; i < cells_.size(); i++) {
      output.writeMessage(2, cells_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getElement());
    }
    for (int i = 0; i < cells_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, cells_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.openmbee.opensysml.proto.DocumentQueryRow)) {
      return super.equals(obj);
    }
    org.openmbee.opensysml.proto.DocumentQueryRow other = (org.openmbee.opensysml.proto.DocumentQueryRow) obj;

    if (hasElement() != other.hasElement()) return false;
    if (hasElement()) {
      if (!getElement()
          .equals(other.getElement())) return false;
    }
    if (!getCellsList()
        .equals(other.getCellsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasElement()) {
      hash = (37 * hash) + ELEMENT_FIELD_NUMBER;
      hash = (53 * hash) + getElement().hashCode();
    }
    if (getCellsCount() > 0) {
      hash = (37 * hash) + CELLS_FIELD_NUMBER;
      hash = (53 * hash) + getCellsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.openmbee.opensysml.proto.DocumentQueryRow parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmbee.opensysml.proto.DocumentQueryRow parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.DocumentQueryRow parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmbee.opensysml.proto.DocumentQueryRow parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.DocumentQueryRow parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmbee.opensysml.proto.DocumentQueryRow parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.DocumentQueryRow parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.openmbee.opensysml.proto.DocumentQueryRow parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.openmbee.opensysml.proto.DocumentQueryRow parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.openmbee.opensysml.proto.DocumentQueryRow parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.DocumentQueryRow parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.openmbee.opensysml.proto.DocumentQueryRow parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.openmbee.opensysml.proto.DocumentQueryRow prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * DocumentQueryRow is one selected element and its projected cells, one per
   * column in column order.
   * </pre>
   *
   * Protobuf type {@code sysml.DocumentQueryRow}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sysml.DocumentQueryRow)
      org.openmbee.opensysml.proto.DocumentQueryRowOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_DocumentQueryRow_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_DocumentQueryRow_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.openmbee.opensysml.proto.DocumentQueryRow.class, org.openmbee.opensysml.proto.DocumentQueryRow.Builder.class);
    }

    // Construct using org.openmbee.opensysml.proto.DocumentQueryRow.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetElementFieldBuilder();
        internalGetCellsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      element_ = null;
      if (elementBuilder_ != null) {
        elementBuilder_.dispose();
        elementBuilder_ = null;
      }
      if (cellsBuilder_ == null) {
        cells_ = java.util.Collections.emptyList();
      } else {
        cells_ = null;
        cellsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_DocumentQueryRow_descriptor;
    }

    @java.lang.Override
    public org.openmbee.opensysml.proto.DocumentQueryRow getDefaultInstanceForType() {
      return org.openmbee.opensysml.proto.DocumentQueryRow.getDefaultInstance();
    }

    @java.lang.Override
    public org.openmbee.opensysml.proto.DocumentQueryRow build() {
      org.openmbee.opensysml.proto.DocumentQueryRow result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.openmbee.opensysml.proto.DocumentQueryRow buildPartial() {
      org.openmbee.opensysml.proto.DocumentQueryRow result = new org.openmbee.opensysml.proto.DocumentQueryRow(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.openmbee.opensysml.proto.DocumentQueryRow result) {
      if (cellsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          cells_ = java.util.Collections.unmodifiableList(cells_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.cells_ = cells_;
      } else {
        result.cells_ = cellsBuilder_.build();
      }
    }

    private void buildPartial0(org.openmbee.opensysml.proto.DocumentQueryRow result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.element_ = elementBuilder_ == null
            ? element_
            : elementBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.openmbee.opensysml.proto.DocumentQueryRow) {
        return mergeFrom((org.openmbee.opensysml.proto.DocumentQueryRow)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.openmbee.opensysml.proto.DocumentQueryRow other) {
      if (other == org.openmbee.opensysml.proto.DocumentQueryRow.getDefaultInstance()) return this;
      if (other.hasElement()) {
        mergeElement(other.getElement());
      }
      if (cellsBuilder_ == null) {
        if (!other.cells_.isEmpty()) {
          if (cells_.isEmpty()) {
            cells_ = other.cells_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureCellsIsMutable();
            cells_.addAll(other.cells_);
          }
          onChanged();
        }
      } else {
        if (!other.cells_.isEmpty()) {
          if (cellsBuilder_.isEmpty()) {
            cellsBuilder_.dispose();
            cellsBuilder_ = null;
            cells_ = other.cells_;
            bitField0_ = (bitField0_ & ~0x00000002);
            cellsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetCellsFieldBuilder() : null;
          } else {
            cellsBuilder_.addAllMessages(other.cells_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetElementFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              org.openmbee.opensysml.proto.DocumentQueryCell m =
                  input.readMessage(
                      org.openmbee.opensysml.proto.DocumentQueryCell.parser(),
                      extensionRegistry);
              if (cellsBuilder_ == null) {
                ensureCellsIsMutable();
                cells_.add(m);
              } else {
                cellsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private org.openmbee.opensysml.proto.DocumentValue element_;
    private com.google.protobuf.SingleFieldBuilder<
        org.openmbee.opensysml.proto.DocumentValue, org.openmbee.opensysml.proto.DocumentValue.Builder, org.openmbee.opensysml.proto.DocumentValueOrBuilder> elementBuilder_;
    /**
     * <pre>
     * The selected element itself, an element value with its qualified name; an
     * object value for a row over an object the service holds; a verdict value
     * for a row `Verdicts` answered; a state value for a row `States` answered;
     * an event value for a row `Events` answered.
     * </pre>
     *
     * <code>.sysml.DocumentValue element = 1 [json_name = "element"];</code>
     * @return Whether the element field is set.
     */
    public boolean hasElement() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * The selected element itself, an element value with its qualified name; an
     * object value for a row over an object the service holds; a verdict value
     * for a row `Verdicts` answered; a state value for a row `States` answered;
     * an event value for a row `Events` answered.
     * </pre>
     *
     * <code>.sysml.DocumentValue element = 1 [json_name = "element"];</code>
     * @return The element.
     */
    public org.openmbee.opensysml.proto.DocumentValue getElement() {
      if (elementBuilder_ == null) {
        return element_ == null ? org.openmbee.opensysml.proto.DocumentValue.getDefaultInstance() : element_;
      } else {
        return elementBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The selected element itself, an element value with its qualified name; an
     * object value for a row over an object the service holds; a verdict value
     * for a row `Verdicts` answered; a state value for a row `States` answered;
     * an event value for a row `Events` answered.
     * </pre>
     *
     * <code>.sysml.DocumentValue element = 1 [json_name = "element"];</code>
     */
    public Builder setElement(org.openmbee.opensysml.proto.DocumentValue value) {
      if (elementBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        element_ = value;
      } else {
        elementBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The selected element itself, an element value with its qualified name; an
     * object value for a row over an object the service holds; a verdict value
     * for a row `Verdicts` answered; a state value for a row `States` answered;
     * an event value for a row `Events` answered.
     * </pre>
     *
     * <code>.sysml.DocumentValue element = 1 [json_name = "element"];</code>
     */
    public Builder setElement(
        org.openmbee.opensysml.proto.DocumentValue.Builder builderForValue) {
      if (elementBuilder_ == null) {
        element_ = builderForValue.build();
      } else {
        elementBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The selected element itself, an element value with its qualified name; an
     * object value for a row over an object the service holds; a verdict value
     * for a row `Verdicts` answered; a state value for a row `States` answered;
     * an event value for a row `Events` answered.
     * </pre>
     *
     * <code>.sysml.DocumentValue element = 1 [json_name = "element"];</code>
     */
    public Builder mergeElement(org.openmbee.opensysml.proto.DocumentValue value) {
      if (elementBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          element_ != null &&
          element_ != org.openmbee.opensysml.proto.DocumentValue.getDefaultInstance()) {
          getElementBuilder().mergeFrom(value);
        } else {
          element_ = value;
        }
      } else {
        elementBuilder_.mergeFrom(value);
      }
      if (element_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * The selected element itself, an element value with its qualified name; an
     * object value for a row over an object the service holds; a verdict value
     * for a row `Verdicts` answered; a state value for a row `States` answered;
     * an event value for a row `Events` answered.
     * </pre>
     *
     * <code>.sysml.DocumentValue element = 1 [json_name = "element"];</code>
     */
    public Builder clearElement() {
      bitField0_ = (bitField0_ & ~0x00000001);
      element_ = null;
      if (elementBuilder_ != null) {
        elementBuilder_.dispose();
        elementBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The selected element itself, an element value with its qualified name; an
     * object value for a row over an object the service holds; a verdict value
     * for a row `Verdicts` answered; a state value for a row `States` answered;
     * an event value for a row `Events` answered.
     * </pre>
     *
     * <code>.sysml.DocumentValue element = 1 [json_name = "element"];</code>
     */
    public org.openmbee.opensysml.proto.DocumentValue.Builder getElementBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetElementFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The selected element itself, an element value with its qualified name; an
     * object value for a row over an object the service holds; a verdict value
     * for a row `Verdicts` answered; a state value for a row `States` answered;
     * an event value for a row `Events` answered.
     * </pre>
     *
     * <code>.sysml.DocumentValue element = 1 [json_name = "element"];</code>
     */
    public org.openmbee.opensysml.proto.DocumentValueOrBuilder getElementOrBuilder() {
      if (elementBuilder_ != null) {
        return elementBuilder_.getMessageOrBuilder();
      } else {
        return element_ == null ?
            org.openmbee.opensysml.proto.DocumentValue.getDefaultInstance() : element_;
      }
    }
    /**
     * <pre>
     * The selected element itself, an element value with its qualified name; an
     * object value for a row over an object the service holds; a verdict value
     * for a row `Verdicts` answered; a state value for a row `States` answered;
     * an event value for a row `Events` answered.
     * </pre>
     *
     * <code>.sysml.DocumentValue element = 1 [json_name = "element"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.openmbee.opensysml.proto.DocumentValue, org.openmbee.opensysml.proto.DocumentValue.Builder, org.openmbee.opensysml.proto.DocumentValueOrBuilder> 
        internalGetElementFieldBuilder() {
      if (elementBuilder_ == null) {
        elementBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.openmbee.opensysml.proto.DocumentValue, org.openmbee.opensysml.proto.DocumentValue.Builder, org.openmbee.opensysml.proto.DocumentValueOrBuilder>(
                getElement(),
                getParentForChildren(),
                isClean());
        element_ = null;
      }
      return elementBuilder_;
    }

    private java.util.List<org.openmbee.opensysml.proto.DocumentQueryCell> cells_ =
      java.util.Collections.emptyList();
    private void ensureCellsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        cells_ = new java.util.ArrayList<org.openmbee.opensysml.proto.DocumentQueryCell>(cells_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        org.openmbee.opensysml.proto.DocumentQueryCell, org.openmbee.opensysml.proto.DocumentQueryCell.Builder, org.openmbee.opensysml.proto.DocumentQueryCellOrBuilder> cellsBuilder_;

    /**
     * <code>repeated .sysml.DocumentQueryCell cells = 2 [json_name = "cells"];</code>
     */
    public java.util.List<org.openmbee.opensysml.proto.DocumentQueryCell> getCellsList() {
      if (cellsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(cells_);
      } else {
        return cellsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .sysml.DocumentQueryCell cells = 2 [json_name = "cells"];</code>
     */
    public int getCellsCount() {
      if (cellsBuilder_ == null) {
        return cells_.size();
      } else {
        return cellsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .sysml.DocumentQueryCell cells = 2 [json_name = "cells"];</code>
     */
    public org.openmbee.opensysml.proto.DocumentQueryCell getCells(int index) {
      if (cellsBuilder_ == null) {
        return cells_.get(index);
      } else {
        return cellsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .sysml.DocumentQueryCell cells = 2 [json_name = "cells"];</code>
     */
    public Builder setCells(
        int index, org.openmbee.opensysml.proto.DocumentQueryCell value) {
      if (cellsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCellsIsMutable();
        cells_.set(index, value);
        onChanged();
      } else {
        cellsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .sysml.DocumentQueryCell cells = 2 [json_name = "cells"];</code>
     */
    public Builder setCells(
        int index, org.openmbee.opensysml.proto.DocumentQueryCell.Builder builderForValue) {
      if (cellsBuilder_ == null) {
        ensureCellsIsMutable();
        cells_.set(index, builderForValue.build());
        onChanged();
      } else {
        cellsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .sysml.DocumentQueryCell cells = 2 [json_name = "cells"];</code>
     */
    public Builder addCells(org.openmbee.opensysml.proto.DocumentQueryCell value) {
      if (cellsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCellsIsMutable();
        cells_.add(value);
        onChanged();
      } else {
        cellsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .sysml.DocumentQueryCell cells = 2 [json_name = "cells"];</code>
     */
    public Builder addCells(
        int index, org.openmbee.opensysml.proto.DocumentQueryCell value) {
      if (cellsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCellsIsMutable();
        cells_.add(index, value);
        onChanged();
      } else {
        cellsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .sysml.DocumentQueryCell cells = 2 [json_name = "cells"];</code>
     */
    public Builder addCells(
        org.openmbee.opensysml.proto.DocumentQueryCell.Builder builderForValue) {
      if (cellsBuilder_ == null) {
        ensureCellsIsMutable();
        cells_.add(builderForValue.build());
        onChanged();
      } else {
        cellsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .sysml.DocumentQueryCell cells = 2 [json_name = "cells"];</code>
     */
    public Builder addCells(
        int index, org.openmbee.opensysml.proto.DocumentQueryCell.Builder builderForValue) {
      if (cellsBuilder_ == null) {
        ensureCellsIsMutable();
        cells_.add(index, builderForValue.build());
        onChanged();
      } else {
        cellsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .sysml.DocumentQueryCell cells = 2 [json_name = "cells"];</code>
     */
    public Builder addAllCells(
        java.lang.Iterable<? extends org.openmbee.opensysml.proto.DocumentQueryCell> values) {
      if (cellsBuilder_ == null) {
        ensureCellsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, cells_);
        onChanged();
      } else {
        cellsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .sysml.DocumentQueryCell cells = 2 [json_name = "cells"];</code>
     */
    public Builder clearCells() {
      if (cellsBuilder_ == null) {
        cells_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        cellsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .sysml.DocumentQueryCell cells = 2 [json_name = "cells"];</code>
     */
    public Builder removeCells(int index) {
      if (cellsBuilder_ == null) {
        ensureCellsIsMutable();
        cells_.remove(index);
        onChanged();
      } else {
        cellsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .sysml.DocumentQueryCell cells = 2 [json_name = "cells"];</code>
     */
    public org.openmbee.opensysml.proto.DocumentQueryCell.Builder getCellsBuilder(
        int index) {
      return internalGetCellsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .sysml.DocumentQueryCell cells = 2 [json_name = "cells"];</code>
     */
    public org.openmbee.opensysml.proto.DocumentQueryCellOrBuilder getCellsOrBuilder(
        int index) {
      if (cellsBuilder_ == null) {
        return cells_.get(index);  } else {
        return cellsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .sysml.DocumentQueryCell cells = 2 [json_name = "cells"];</code>
     */
    public java.util.List<? extends org.openmbee.opensysml.proto.DocumentQueryCellOrBuilder> 
         getCellsOrBuilderList() {
      if (cellsBuilder_ != null) {
        return cellsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(cells_);
      }
    }
    /**
     * <code>repeated .sysml.DocumentQueryCell cells = 2 [json_name = "cells"];</code>
     */
    public org.openmbee.opensysml.proto.DocumentQueryCell.Builder addCellsBuilder() {
      return internalGetCellsFieldBuilder().addBuilder(
          org.openmbee.opensysml.proto.DocumentQueryCell.getDefaultInstance());
    }
    /**
     * <code>repeated .sysml.DocumentQueryCell cells = 2 [json_name = "cells"];</code>
     */
    public org.openmbee.opensysml.proto.DocumentQueryCell.Builder addCellsBuilder(
        int index) {
      return internalGetCellsFieldBuilder().addBuilder(
          index, org.openmbee.opensysml.proto.DocumentQueryCell.getDefaultInstance());
    }
    /**
     * <code>repeated .sysml.DocumentQueryCell cells = 2 [json_name = "cells"];</code>
     */
    public java.util.List<org.openmbee.opensysml.proto.DocumentQueryCell.Builder> 
         getCellsBuilderList() {
      return internalGetCellsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        org.openmbee.opensysml.proto.DocumentQueryCell, org.openmbee.opensysml.proto.DocumentQueryCell.Builder, org.openmbee.opensysml.proto.DocumentQueryCellOrBuilder> 
        internalGetCellsFieldBuilder() {
      if (cellsBuilder_ == null) {
        cellsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            org.openmbee.opensysml.proto.DocumentQueryCell, org.openmbee.opensysml.proto.DocumentQueryCell.Builder, org.openmbee.opensysml.proto.DocumentQueryCellOrBuilder>(
                cells_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        cells_ = null;
      }
      return cellsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:sysml.DocumentQueryRow)
  }

  // @@protoc_insertion_point(class_scope:sysml.DocumentQueryRow)
  private static final org.openmbee.opensysml.proto.DocumentQueryRow DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.openmbee.opensysml.proto.DocumentQueryRow();
  }

  public static org.openmbee.opensysml.proto.DocumentQueryRow getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DocumentQueryRow>
      PARSER = new com.google.protobuf.AbstractParser<DocumentQueryRow>() {
    @java.lang.Override
    public DocumentQueryRow parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DocumentQueryRow> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DocumentQueryRow> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.openmbee.opensysml.proto.DocumentQueryRow getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

