// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package org.openmbee.opensysml.proto;

@com.google.protobuf.Generated
public interface InstantiateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sysml.InstantiateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.sysml.Instance instance = 1 [json_name = "instance"];</code>
   * @return Whether the instance field is set.
   */
  boolean hasInstance();
  /**
   * <code>.sysml.Instance instance = 1 [json_name = "instance"];</code>
   * @return The instance.
   */
  org.openmbee.opensysml.proto.Instance getInstance();
  /**
   * <code>.sysml.Instance instance = 1 [json_name = "instance"];</code>
   */
  org.openmbee.opensysml.proto.InstanceOrBuilder getInstanceOrBuilder();

  /**
   * <code>string error = 2 [json_name = "error"];</code>
   * @return The error.
   */
  java.lang.String getError();
  /**
   * <code>string error = 2 [json_name = "error"];</code>
   * @return The bytes for error.
   */
  com.google.protobuf.ByteString
      getErrorBytes();

  /**
   * <code>repeated .sysml.Diagnostic diagnostics = 3 [json_name = "diagnostics"];</code>
   */
  java.util.List<org.openmbee.opensysml.proto.Diagnostic> 
      getDiagnosticsList();
  /**
   * <code>repeated .sysml.Diagnostic diagnostics = 3 [json_name = "diagnostics"];</code>
   */
  org.openmbee.opensysml.proto.Diagnostic getDiagnostics(int index);
  /**
   * <code>repeated .sysml.Diagnostic diagnostics = 3 [json_name = "diagnostics"];</code>
   */
  int getDiagnosticsCount();
  /**
   * <code>repeated .sysml.Diagnostic diagnostics = 3 [json_name = "diagnostics"];</code>
   */
  java.util.List<? extends org.openmbee.opensysml.proto.DiagnosticOrBuilder> 
      getDiagnosticsOrBuilderList();
  /**
   * <code>repeated .sysml.Diagnostic diagnostics = 3 [json_name = "diagnostics"];</code>
   */
  org.openmbee.opensysml.proto.DiagnosticOrBuilder getDiagnosticsOrBuilder(
      int index);

  /**
   * <pre>
   * Every instance reachable from `instance`, including `instance` itself, so a
   * client can resolve an `instance_id` feature value without a follow-up RPC.
   * </pre>
   *
   * <code>repeated .sysml.Instance instances = 4 [json_name = "instances"];</code>
   */
  java.util.List<org.openmbee.opensysml.proto.Instance> 
      getInstancesList();
  /**
   * <pre>
   * Every instance reachable from `instance`, including `instance` itself, so a
   * client can resolve an `instance_id` feature value without a follow-up RPC.
   * </pre>
   *
   * <code>repeated .sysml.Instance instances = 4 [json_name = "instances"];</code>
   */
  org.openmbee.opensysml.proto.Instance getInstances(int index);
  /**
   * <pre>
   * Every instance reachable from `instance`, including `instance` itself, so a
   * client can resolve an `instance_id` feature value without a follow-up RPC.
   * </pre>
   *
   * <code>repeated .sysml.Instance instances = 4 [json_name = "instances"];</code>
   */
  int getInstancesCount();
  /**
   * <pre>
   * Every instance reachable from `instance`, including `instance` itself, so a
   * client can resolve an `instance_id` feature value without a follow-up RPC.
   * </pre>
   *
   * <code>repeated .sysml.Instance instances = 4 [json_name = "instances"];</code>
   */
  java.util.List<? extends org.openmbee.opensysml.proto.InstanceOrBuilder> 
      getInstancesOrBuilderList();
  /**
   * <pre>
   * Every instance reachable from `instance`, including `instance` itself, so a
   * client can resolve an `instance_id` feature value without a follow-up RPC.
   * </pre>
   *
   * <code>repeated .sysml.Instance instances = 4 [json_name = "instances"];</code>
   */
  org.openmbee.opensysml.proto.InstanceOrBuilder getInstancesOrBuilder(
      int index);
}
