// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package org.openmbee.opensysml.proto;

/**
 * <pre>
 * ParseFileResponse contains parsed model info
 * </pre>
 *
 * Protobuf type {@code sysml.ParseFileResponse}
 */
@com.google.protobuf.Generated
public final class ParseFileResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:sysml.ParseFileResponse)
    ParseFileResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "ParseFileResponse");
  }
  // Use ParseFileResponse.newBuilder() to construct.
  private ParseFileResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ParseFileResponse() {
    modelHash_ = "";
    diagnostics_ = java.util.Collections.emptyList();
    error_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_ParseFileResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_ParseFileResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.openmbee.opensysml.proto.ParseFileResponse.class, org.openmbee.opensysml.proto.ParseFileResponse.Builder.class);
  }

  private int bitField0_;
  public static final int MODEL_HASH_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object modelHash_ = "";
  /**
   * <pre>
   * Cache key for subsequent requests
   * </pre>
   *
   * <code>string model_hash = 1 [json_name = "modelHash"];</code>
   * @return The modelHash.
   */
  @java.lang.Override
  public java.lang.String getModelHash() {
    java.lang.Object ref = modelHash_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      modelHash_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Cache key for subsequent requests
   * </pre>
   *
   * <code>string model_hash = 1 [json_name = "modelHash"];</code>
   * @return The bytes for modelHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModelHashBytes() {
    java.lang.Object ref = modelHash_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      modelHash_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROOT_FIELD_NUMBER = 2;
  private org.openmbee.opensysml.proto.SymbolInfo root_;
  /**
   * <pre>
   * Root namespace
   * </pre>
   *
   * <code>.sysml.SymbolInfo root = 2 [json_name = "root"];</code>
   * @return Whether the root field is set.
   */
  @java.lang.Override
  public boolean hasRoot() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Root namespace
   * </pre>
   *
   * <code>.sysml.SymbolInfo root = 2 [json_name = "root"];</code>
   * @return The root.
   */
  @java.lang.Override
  public org.openmbee.opensysml.proto.SymbolInfo getRoot() {
    return root_ == null ? org.openmbee.opensysml.proto.SymbolInfo.getDefaultInstance() : root_;
  }
  /**
   * <pre>
   * Root namespace
   * </pre>
   *
   * <code>.sysml.SymbolInfo root = 2 [json_name = "root"];</code>
   */
  @java.lang.Override
  public org.openmbee.opensysml.proto.SymbolInfoOrBuilder getRootOrBuilder() {
    return root_ == null ? org.openmbee.opensysml.proto.SymbolInfo.getDefaultInstance() : root_;
  }

  public static final int DIAGNOSTICS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<org.openmbee.opensysml.proto.Diagnostic> diagnostics_;
  /**
   * <code>repeated .sysml.Diagnostic diagnostics = 3 [json_name = "diagnostics"];</code>
   */
  @java.lang.Override
  public java.util.List<org.openmbee.opensysml.proto.Diagnostic> getDiagnosticsList() {
    return diagnostics_;
  }
  /**
   * <code>repeated .sysml.Diagnostic diagnostics = 3 [json_name = "diagnostics"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.openmbee.opensysml.proto.DiagnosticOrBuilder> 
      getDiagnosticsOrBuilderList() {
    return diagnostics_;
  }
  /**
   * <code>repeated .sysml.Diagnostic diagnostics = 3 [json_name = "diagnostics"];</code>
   */
  @java.lang.Override
  public int getDiagnosticsCount() {
    return diagnostics_.size();
  }
  /**
   * <code>repeated .sysml.Diagnostic diagnostics = 3 [json_name = "diagnostics"];</code>
   */
  @java.lang.Override
  public org.openmbee.opensysml.proto.Diagnostic getDiagnostics(int index) {
    return diagnostics_.get(index);
  }
  /**
   * <code>repeated .sysml.Diagnostic diagnostics = 3 [json_name = "diagnostics"];</code>
   */
  @java.lang.Override
  public org.openmbee.opensysml.proto.DiagnosticOrBuilder getDiagnosticsOrBuilder(
      int index) {
    return diagnostics_.get(index);
  }

  public static final int ERROR_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object error_ = "";
  /**
   * <pre>
   * Critical failure message if any
   * </pre>
   *
   * <code>string error = 4 [json_name = "error"];</code>
   * @return The error.
   */
  @java.lang.Override
  public java.lang.String getError() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      error_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Critical failure message if any
   * </pre>
   *
   * <code>string error = 4 [json_name = "error"];</code>
   * @return The bytes for error.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorBytes() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      error_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(modelHash_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, modelHash_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getRoot());
    }
    for (int i = 0; i < diagnostics_.size(); i++) {
      output.writeMessage(3, diagnostics_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(error_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, error_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(modelHash_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, modelHash_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getRoot());
    }
    for (int i = 0; i < diagnostics_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, diagnostics_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(error_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, error_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.openmbee.opensysml.proto.ParseFileResponse)) {
      return super.equals(obj);
    }
    org.openmbee.opensysml.proto.ParseFileResponse other = (org.openmbee.opensysml.proto.ParseFileResponse) obj;

    if (!getModelHash()
        .equals(other.getModelHash())) return false;
    if (hasRoot() != other.hasRoot()) return false;
    if (hasRoot()) {
      if (!getRoot()
          .equals(other.getRoot())) return false;
    }
    if (!getDiagnosticsList()
        .equals(other.getDiagnosticsList())) return false;
    if (!getError()
        .equals(other.getError())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MODEL_HASH_FIELD_NUMBER;
    hash = (53 * hash) + getModelHash().hashCode();
    if (hasRoot()) {
      hash = (37 * hash) + ROOT_FIELD_NUMBER;
      hash = (53 * hash) + getRoot().hashCode();
    }
    if (getDiagnosticsCount() > 0) {
      hash = (37 * hash) + DIAGNOSTICS_FIELD_NUMBER;
      hash = (53 * hash) + getDiagnosticsList().hashCode();
    }
    hash = (37 * hash) + ERROR_FIELD_NUMBER;
    hash = (53 * hash) + getError().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.openmbee.opensysml.proto.ParseFileResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmbee.opensysml.proto.ParseFileResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.ParseFileResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmbee.opensysml.proto.ParseFileResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.ParseFileResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmbee.opensysml.proto.ParseFileResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.ParseFileResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.openmbee.opensysml.proto.ParseFileResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.openmbee.opensysml.proto.ParseFileResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.openmbee.opensysml.proto.ParseFileResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.ParseFileResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.openmbee.opensysml.proto.ParseFileResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.openmbee.opensysml.proto.ParseFileResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ParseFileResponse contains parsed model info
   * </pre>
   *
   * Protobuf type {@code sysml.ParseFileResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sysml.ParseFileResponse)
      org.openmbee.opensysml.proto.ParseFileResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_ParseFileResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_ParseFileResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.openmbee.opensysml.proto.ParseFileResponse.class, org.openmbee.opensysml.proto.ParseFileResponse.Builder.class);
    }

    // Construct using org.openmbee.opensysml.proto.ParseFileResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetRootFieldBuilder();
        internalGetDiagnosticsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      modelHash_ = "";
      root_ = null;
      if (rootBuilder_ != null) {
        rootBuilder_.dispose();
        rootBuilder_ = null;
      }
      if (diagnosticsBuilder_ == null) {
        diagnostics_ = java.util.Collections.emptyList();
      } else {
        diagnostics_ = null;
        diagnosticsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      error_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_ParseFileResponse_descriptor;
    }

    @java.lang.Override
    public org.openmbee.opensysml.proto.ParseFileResponse getDefaultInstanceForType() {
      return org.openmbee.opensysml.proto.ParseFileResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.openmbee.opensysml.proto.ParseFileResponse build() {
      org.openmbee.opensysml.proto.ParseFileResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.openmbee.opensysml.proto.ParseFileResponse buildPartial() {
      org.openmbee.opensysml.proto.ParseFileResponse result = new org.openmbee.opensysml.proto.ParseFileResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.openmbee.opensysml.proto.ParseFileResponse result) {
      if (diagnosticsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          diagnostics_ = java.util.Collections.unmodifiableList(diagnostics_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.diagnostics_ = diagnostics_;
      } else {
        result.diagnostics_ = diagnosticsBuilder_.build();
      }
    }

    private void buildPartial0(org.openmbee.opensysml.proto.ParseFileResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.modelHash_ = modelHash_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.root_ = rootBuilder_ == null
            ? root_
            : rootBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.error_ = error_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.openmbee.opensysml.proto.ParseFileResponse) {
        return mergeFrom((org.openmbee.opensysml.proto.ParseFileResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.openmbee.opensysml.proto.ParseFileResponse other) {
      if (other == org.openmbee.opensysml.proto.ParseFileResponse.getDefaultInstance()) return this;
      if (!other.getModelHash().isEmpty()) {
        modelHash_ = other.modelHash_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasRoot()) {
        mergeRoot(other.getRoot());
      }
      if (diagnosticsBuilder_ == null) {
        if (!other.diagnostics_.isEmpty()) {
          if (diagnostics_.isEmpty()) {
            diagnostics_ = other.diagnostics_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureDiagnosticsIsMutable();
            diagnostics_.addAll(other.diagnostics_);
          }
          onChanged();
        }
      } else {
        if (!other.diagnostics_.isEmpty()) {
          if (diagnosticsBuilder_.isEmpty()) {
            diagnosticsBuilder_.dispose();
            diagnosticsBuilder_ = null;
            diagnostics_ = other.diagnostics_;
            bitField0_ = (bitField0_ & ~0x00000004);
            diagnosticsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetDiagnosticsFieldBuilder() : null;
          } else {
            diagnosticsBuilder_.addAllMessages(other.diagnostics_);
          }
        }
      }
      if (!other.getError().isEmpty()) {
        error_ = other.error_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              modelHash_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetRootFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              org.openmbee.opensysml.proto.Diagnostic m =
                  input.readMessage(
                      org.openmbee.opensysml.proto.Diagnostic.parser(),
                      extensionRegistry);
              if (diagnosticsBuilder_ == null) {
                ensureDiagnosticsIsMutable();
                diagnostics_.add(m);
              } else {
                diagnosticsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 34: {
              error_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object modelHash_ = "";
    /**
     * <pre>
     * Cache key for subsequent requests
     * </pre>
     *
     * <code>string model_hash = 1 [json_name = "modelHash"];</code>
     * @return The modelHash.
     */
    public java.lang.String getModelHash() {
      java.lang.Object ref = modelHash_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        modelHash_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Cache key for subsequent requests
     * </pre>
     *
     * <code>string model_hash = 1 [json_name = "modelHash"];</code>
     * @return The bytes for modelHash.
     */
    public com.google.protobuf.ByteString
        getModelHashBytes() {
      java.lang.Object ref = modelHash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modelHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Cache key for subsequent requests
     * </pre>
     *
     * <code>string model_hash = 1 [json_name = "modelHash"];</code>
     * @param value The modelHash to set.
     * @return This builder for chaining.
     */
    public Builder setModelHash(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      modelHash_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Cache key for subsequent requests
     * </pre>
     *
     * <code>string model_hash = 1 [json_name = "modelHash"];</code>
     * @return This builder for chaining.
     */
    public Builder clearModelHash() {
      modelHash_ = getDefaultInstance().getModelHash();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Cache key for subsequent requests
     * </pre>
     *
     * <code>string model_hash = 1 [json_name = "modelHash"];</code>
     * @param value The bytes for modelHash to set.
     * @return This builder for chaining.
     */
    public Builder setModelHashBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      modelHash_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private org.openmbee.opensysml.proto.SymbolInfo root_;
    private com.google.protobuf.SingleFieldBuilder<
        org.openmbee.opensysml.proto.SymbolInfo, org.openmbee.opensysml.proto.SymbolInfo.Builder, org.openmbee.opensysml.proto.SymbolInfoOrBuilder> rootBuilder_;
    /**
     * <pre>
     * Root namespace
     * </pre>
     *
     * <code>.sysml.SymbolInfo root = 2 [json_name = "root"];</code>
     * @return Whether the root field is set.
     */
    public boolean hasRoot() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Root namespace
     * </pre>
     *
     * <code>.sysml.SymbolInfo root = 2 [json_name = "root"];</code>
     * @return The root.
     */
    public org.openmbee.opensysml.proto.SymbolInfo getRoot() {
      if (rootBuilder_ == null) {
        return root_ == null ? org.openmbee.opensysml.proto.SymbolInfo.getDefaultInstance() : root_;
      } else {
        return rootBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Root namespace
     * </pre>
     *
     * <code>.sysml.SymbolInfo root = 2 [json_name = "root"];</code>
     */
    public Builder setRoot(org.openmbee.opensysml.proto.SymbolInfo value) {
      if (rootBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        root_ = value;
      } else {
        rootBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Root namespace
     * </pre>
     *
     * <code>.sysml.SymbolInfo root = 2 [json_name = "root"];</code>
     */
    public Builder setRoot(
        org.openmbee.opensysml.proto.SymbolInfo.Builder builderForValue) {
      if (rootBuilder_ == null) {
        root_ = builderForValue.build();
      } else {
        rootBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Root namespace
     * </pre>
     *
     * <code>.sysml.SymbolInfo root = 2 [json_name = "root"];</code>
     */
    public Builder mergeRoot(org.openmbee.opensysml.proto.SymbolInfo value) {
      if (rootBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          root_ != null &&
          root_ != org.openmbee.opensysml.proto.SymbolInfo.getDefaultInstance()) {
          getRootBuilder().mergeFrom(value);
        } else {
          root_ = value;
        }
      } else {
        rootBuilder_.mergeFrom(value);
      }
      if (root_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Root namespace
     * </pre>
     *
     * <code>.sysml.SymbolInfo root = 2 [json_name = "root"];</code>
     */
    public Builder clearRoot() {
      bitField0_ = (bitField0_ & ~0x00000002);
      root_ = null;
      if (rootBuilder_ != null) {
        rootBuilder_.dispose();
        rootBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Root namespace
     * </pre>
     *
     * <code>.sysml.SymbolInfo root = 2 [json_name = "root"];</code>
     */
    public org.openmbee.opensysml.proto.SymbolInfo.Builder getRootBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetRootFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Root namespace
     * </pre>
     *
     * <code>.sysml.SymbolInfo root = 2 [json_name = "root"];</code>
     */
    public org.openmbee.opensysml.proto.SymbolInfoOrBuilder getRootOrBuilder() {
      if (rootBuilder_ != null) {
        return rootBuilder_.getMessageOrBuilder();
      } else {
        return root_ == null ?
            org.openmbee.opensysml.proto.SymbolInfo.getDefaultInstance() : root_;
      }
    }
    /**
     * <pre>
     * Root namespace
     * </pre>
     *
     * <code>.sysml.SymbolInfo root = 2 [json_name = "root"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.openmbee.opensysml.proto.SymbolInfo, org.openmbee.opensysml.proto.SymbolInfo.Builder, org.openmbee.opensysml.proto.SymbolInfoOrBuilder> 
        internalGetRootFieldBuilder() {
      if (rootBuilder_ == null) {
        rootBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.openmbee.opensysml.proto.SymbolInfo, org.openmbee.opensysml.proto.SymbolInfo.Builder, org.openmbee.opensysml.proto.SymbolInfoOrBuilder>(
                getRoot(),
                getParentForChildren(),
                isClean());
        root_ = null;
      }
      return rootBuilder_;
    }

    private java.util.List<org.openmbee.opensysml.proto.Diagnostic> diagnostics_ =
      java.util.Collections.emptyList();
    private void ensureDiagnosticsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        diagnostics_ = new java.util.ArrayList<org.openmbee.opensysml.proto.Diagnostic>(diagnostics_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        org.openmbee.opensysml.proto.Diagnostic, org.openmbee.opensysml.proto.Diagnostic.Builder, org.openmbee.opensysml.proto.DiagnosticOrBuilder> diagnosticsBuilder_;

    /**
     * <code>repeated .sysml.Diagnostic diagnostics = 3 [json_name = "diagnostics"];</code>
     */
    public java.util.List<org.openmbee.opensysml.proto.Diagnostic> getDiagnosticsList() {
      if (diagnosticsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(diagnostics_);
      } else {
        return diagnosticsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .sysml.Diagnostic diagnostics = 3 [json_name = "diagnostics"];</code>
     */
    public int getDiagnosticsCount() {
      if (diagnosticsBuilder_ == null) {
        return diagnostics_.size();
      } else {
        return diagnosticsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .sysml.Diagnostic diagnostics = 3 [json_name = "diagnostics"];</code>
     */
    public org.openmbee.opensysml.proto.Diagnostic getDiagnostics(int index) {
      if (diagnosticsBuilder_ == null) {
        return diagnostics_.get(index);
      } else {
        return diagnosticsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .sysml.Diagnostic diagnostics = 3 [json_name = "diagnostics"];</code>
     */
    public Builder setDiagnostics(
        int index, org.openmbee.opensysml.proto.Diagnostic value) {
      if (diagnosticsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDiagnosticsIsMutable();
        diagnostics_.set(index, value);
        onChanged();
      } else {
        diagnosticsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .sysml.Diagnostic diagnostics = 3 [json_name = "diagnostics"];</code>
     */
    public Builder setDiagnostics(
        int index, org.openmbee.opensysml.proto.Diagnostic.Builder builderForValue) {
      if (diagnosticsBuilder_ == null) {
        ensureDiagnosticsIsMutable();
        diagnostics_.set(index, builderForValue.build());
        onChanged();
      } else {
        diagnosticsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .sysml.Diagnostic diagnostics = 3 [json_name = "diagnostics"];</code>
     */
    public Builder addDiagnostics(org.openmbee.opensysml.proto.Diagnostic value) {
      if (diagnosticsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDiagnosticsIsMutable();
        diagnostics_.add(value);
        onChanged();
      } else {
        diagnosticsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .sysml.Diagnostic diagnostics = 3 [json_name = "diagnostics"];</code>
     */
    public Builder addDiagnostics(
        int index, org.openmbee.opensysml.proto.Diagnostic value) {
      if (diagnosticsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDiagnosticsIsMutable();
        diagnostics_.add(index, value);
        onChanged();
      } else {
        diagnosticsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .sysml.Diagnostic diagnostics = 3 [json_name = "diagnostics"];</code>
     */
    public Builder addDiagnostics(
        org.openmbee.opensysml.proto.Diagnostic.Builder builderForValue) {
      if (diagnosticsBuilder_ == null) {
        ensureDiagnosticsIsMutable();
        diagnostics_.add(builderForValue.build());
        onChanged();
      } else {
        diagnosticsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .sysml.Diagnostic diagnostics = 3 [json_name = "diagnostics"];</code>
     */
    public Builder addDiagnostics(
        int index, org.openmbee.opensysml.proto.Diagnostic.Builder builderForValue) {
      if (diagnosticsBuilder_ == null) {
        ensureDiagnosticsIsMutable();
        diagnostics_.add(index, builderForValue.build());
        onChanged();
      } else {
        diagnosticsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .sysml.Diagnostic diagnostics = 3 [json_name = "diagnostics"];</code>
     */
    public Builder addAllDiagnostics(
        java.lang.Iterable<? extends org.openmbee.opensysml.proto.Diagnostic> values) {
      if (diagnosticsBuilder_ == null) {
        ensureDiagnosticsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, diagnostics_);
        onChanged();
      } else {
        diagnosticsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .sysml.Diagnostic diagnostics = 3 [json_name = "diagnostics"];</code>
     */
    public Builder clearDiagnostics() {
      if (diagnosticsBuilder_ == null) {
        diagnostics_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        diagnosticsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .sysml.Diagnostic diagnostics = 3 [json_name = "diagnostics"];</code>
     */
    public Builder removeDiagnostics(int index) {
      if (diagnosticsBuilder_ == null) {
        ensureDiagnosticsIsMutable();
        diagnostics_.remove(index);
        onChanged();
      } else {
        diagnosticsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .sysml.Diagnostic diagnostics = 3 [json_name = "diagnostics"];</code>
     */
    public org.openmbee.opensysml.proto.Diagnostic.Builder getDiagnosticsBuilder(
        int index) {
      return internalGetDiagnosticsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .sysml.Diagnostic diagnostics = 3 [json_name = "diagnostics"];</code>
     */
    public org.openmbee.opensysml.proto.DiagnosticOrBuilder getDiagnosticsOrBuilder(
        int index) {
      if (diagnosticsBuilder_ == null) {
        return diagnostics_.get(index);  } else {
        return diagnosticsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .sysml.Diagnostic diagnostics = 3 [json_name = "diagnostics"];</code>
     */
    public java.util.List<? extends org.openmbee.opensysml.proto.DiagnosticOrBuilder> 
         getDiagnosticsOrBuilderList() {
      if (diagnosticsBuilder_ != null) {
        return diagnosticsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(diagnostics_);
      }
    }
    /**
     * <code>repeated .sysml.Diagnostic diagnostics = 3 [json_name = "diagnostics"];</code>
     */
    public org.openmbee.opensysml.proto.Diagnostic.Builder addDiagnosticsBuilder() {
      return internalGetDiagnosticsFieldBuilder().addBuilder(
          org.openmbee.opensysml.proto.Diagnostic.getDefaultInstance());
    }
    /**
     * <code>repeated .sysml.Diagnostic diagnostics = 3 [json_name = "diagnostics"];</code>
     */
    public org.openmbee.opensysml.proto.Diagnostic.Builder addDiagnosticsBuilder(
        int index) {
      return internalGetDiagnosticsFieldBuilder().addBuilder(
          index, org.openmbee.opensysml.proto.Diagnostic.getDefaultInstance());
    }
    /**
     * <code>repeated .sysml.Diagnostic diagnostics = 3 [json_name = "diagnostics"];</code>
     */
    public java.util.List<org.openmbee.opensysml.proto.Diagnostic.Builder> 
         getDiagnosticsBuilderList() {
      return internalGetDiagnosticsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        org.openmbee.opensysml.proto.Diagnostic, org.openmbee.opensysml.proto.Diagnostic.Builder, org.openmbee.opensysml.proto.DiagnosticOrBuilder> 
        internalGetDiagnosticsFieldBuilder() {
      if (diagnosticsBuilder_ == null) {
        diagnosticsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            org.openmbee.opensysml.proto.Diagnostic, org.openmbee.opensysml.proto.Diagnostic.Builder, org.openmbee.opensysml.proto.DiagnosticOrBuilder>(
                diagnostics_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        diagnostics_ = null;
      }
      return diagnosticsBuilder_;
    }

    private java.lang.Object error_ = "";
    /**
     * <pre>
     * Critical failure message if any
     * </pre>
     *
     * <code>string error = 4 [json_name = "error"];</code>
     * @return The error.
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        error_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Critical failure message if any
     * </pre>
     *
     * <code>string error = 4 [json_name = "error"];</code>
     * @return The bytes for error.
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Critical failure message if any
     * </pre>
     *
     * <code>string error = 4 [json_name = "error"];</code>
     * @param value The error to set.
     * @return This builder for chaining.
     */
    public Builder setError(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      error_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Critical failure message if any
     * </pre>
     *
     * <code>string error = 4 [json_name = "error"];</code>
     * @return This builder for chaining.
     */
    public Builder clearError() {
      error_ = getDefaultInstance().getError();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Critical failure message if any
     * </pre>
     *
     * <code>string error = 4 [json_name = "error"];</code>
     * @param value The bytes for error to set.
     * @return This builder for chaining.
     */
    public Builder setErrorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      error_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sysml.ParseFileResponse)
  }

  // @@protoc_insertion_point(class_scope:sysml.ParseFileResponse)
  private static final org.openmbee.opensysml.proto.ParseFileResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.openmbee.opensysml.proto.ParseFileResponse();
  }

  public static org.openmbee.opensysml.proto.ParseFileResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ParseFileResponse>
      PARSER = new com.google.protobuf.AbstractParser<ParseFileResponse>() {
    @java.lang.Override
    public ParseFileResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ParseFileResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ParseFileResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.openmbee.opensysml.proto.ParseFileResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

