// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package org.openmbee.opensysml.proto;

/**
 * <pre>
 * RenderViewRequest names a declared view or targeted pseudo-view to render.
 * </pre>
 *
 * Protobuf type {@code sysml.RenderViewRequest}
 */
@com.google.protobuf.Generated
public final class RenderViewRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:sysml.RenderViewRequest)
    RenderViewRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "RenderViewRequest");
  }
  // Use RenderViewRequest.newBuilder() to construct.
  private RenderViewRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RenderViewRequest() {
    modelHash_ = "";
    view_ = "";
    ports_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_RenderViewRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_RenderViewRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.openmbee.opensysml.proto.RenderViewRequest.class, org.openmbee.opensysml.proto.RenderViewRequest.Builder.class);
  }

  public static final int MODEL_HASH_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object modelHash_ = "";
  /**
   * <code>string model_hash = 1 [json_name = "modelHash"];</code>
   * @return The modelHash.
   */
  @java.lang.Override
  public java.lang.String getModelHash() {
    java.lang.Object ref = modelHash_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      modelHash_ = s;
      return s;
    }
  }
  /**
   * <code>string model_hash = 1 [json_name = "modelHash"];</code>
   * @return The bytes for modelHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModelHashBytes() {
    java.lang.Object ref = modelHash_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      modelHash_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VIEW_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object view_ = "";
  /**
   * <pre>
   * A qualified view name or "#&lt;kind&gt;:&lt;qualified name&gt;" pseudo-view.
   * </pre>
   *
   * <code>string view = 2 [json_name = "view"];</code>
   * @return The view.
   */
  @java.lang.Override
  public java.lang.String getView() {
    java.lang.Object ref = view_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      view_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * A qualified view name or "#&lt;kind&gt;:&lt;qualified name&gt;" pseudo-view.
   * </pre>
   *
   * <code>string view = 2 [json_name = "view"];</code>
   * @return The bytes for view.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getViewBytes() {
    java.lang.Object ref = view_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      view_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PORTS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object ports_ = "";
  /**
   * <pre>
   * "" or "minimal" (the default), or "full", as view.ParsePorts reads it.
   * </pre>
   *
   * <code>string ports = 3 [json_name = "ports"];</code>
   * @return The ports.
   */
  @java.lang.Override
  public java.lang.String getPorts() {
    java.lang.Object ref = ports_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ports_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * "" or "minimal" (the default), or "full", as view.ParsePorts reads it.
   * </pre>
   *
   * <code>string ports = 3 [json_name = "ports"];</code>
   * @return The bytes for ports.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPortsBytes() {
    java.lang.Object ref = ports_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ports_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(modelHash_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, modelHash_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(view_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, view_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ports_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, ports_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(modelHash_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, modelHash_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(view_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, view_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ports_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, ports_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.openmbee.opensysml.proto.RenderViewRequest)) {
      return super.equals(obj);
    }
    org.openmbee.opensysml.proto.RenderViewRequest other = (org.openmbee.opensysml.proto.RenderViewRequest) obj;

    if (!getModelHash()
        .equals(other.getModelHash())) return false;
    if (!getView()
        .equals(other.getView())) return false;
    if (!getPorts()
        .equals(other.getPorts())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MODEL_HASH_FIELD_NUMBER;
    hash = (53 * hash) + getModelHash().hashCode();
    hash = (37 * hash) + VIEW_FIELD_NUMBER;
    hash = (53 * hash) + getView().hashCode();
    hash = (37 * hash) + PORTS_FIELD_NUMBER;
    hash = (53 * hash) + getPorts().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.openmbee.opensysml.proto.RenderViewRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmbee.opensysml.proto.RenderViewRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.RenderViewRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmbee.opensysml.proto.RenderViewRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.RenderViewRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmbee.opensysml.proto.RenderViewRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.RenderViewRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.openmbee.opensysml.proto.RenderViewRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.openmbee.opensysml.proto.RenderViewRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.openmbee.opensysml.proto.RenderViewRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.RenderViewRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.openmbee.opensysml.proto.RenderViewRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.openmbee.opensysml.proto.RenderViewRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * RenderViewRequest names a declared view or targeted pseudo-view to render.
   * </pre>
   *
   * Protobuf type {@code sysml.RenderViewRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sysml.RenderViewRequest)
      org.openmbee.opensysml.proto.RenderViewRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_RenderViewRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_RenderViewRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.openmbee.opensysml.proto.RenderViewRequest.class, org.openmbee.opensysml.proto.RenderViewRequest.Builder.class);
    }

    // Construct using org.openmbee.opensysml.proto.RenderViewRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      modelHash_ = "";
      view_ = "";
      ports_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_RenderViewRequest_descriptor;
    }

    @java.lang.Override
    public org.openmbee.opensysml.proto.RenderViewRequest getDefaultInstanceForType() {
      return org.openmbee.opensysml.proto.RenderViewRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.openmbee.opensysml.proto.RenderViewRequest build() {
      org.openmbee.opensysml.proto.RenderViewRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.openmbee.opensysml.proto.RenderViewRequest buildPartial() {
      org.openmbee.opensysml.proto.RenderViewRequest result = new org.openmbee.opensysml.proto.RenderViewRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.openmbee.opensysml.proto.RenderViewRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.modelHash_ = modelHash_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.view_ = view_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.ports_ = ports_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.openmbee.opensysml.proto.RenderViewRequest) {
        return mergeFrom((org.openmbee.opensysml.proto.RenderViewRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.openmbee.opensysml.proto.RenderViewRequest other) {
      if (other == org.openmbee.opensysml.proto.RenderViewRequest.getDefaultInstance()) return this;
      if (!other.getModelHash().isEmpty()) {
        modelHash_ = other.modelHash_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getView().isEmpty()) {
        view_ = other.view_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getPorts().isEmpty()) {
        ports_ = other.ports_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              modelHash_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              view_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              ports_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object modelHash_ = "";
    /**
     * <code>string model_hash = 1 [json_name = "modelHash"];</code>
     * @return The modelHash.
     */
    public java.lang.String getModelHash() {
      java.lang.Object ref = modelHash_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        modelHash_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string model_hash = 1 [json_name = "modelHash"];</code>
     * @return The bytes for modelHash.
     */
    public com.google.protobuf.ByteString
        getModelHashBytes() {
      java.lang.Object ref = modelHash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modelHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string model_hash = 1 [json_name = "modelHash"];</code>
     * @param value The modelHash to set.
     * @return This builder for chaining.
     */
    public Builder setModelHash(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      modelHash_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string model_hash = 1 [json_name = "modelHash"];</code>
     * @return This builder for chaining.
     */
    public Builder clearModelHash() {
      modelHash_ = getDefaultInstance().getModelHash();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string model_hash = 1 [json_name = "modelHash"];</code>
     * @param value The bytes for modelHash to set.
     * @return This builder for chaining.
     */
    public Builder setModelHashBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      modelHash_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object view_ = "";
    /**
     * <pre>
     * A qualified view name or "#&lt;kind&gt;:&lt;qualified name&gt;" pseudo-view.
     * </pre>
     *
     * <code>string view = 2 [json_name = "view"];</code>
     * @return The view.
     */
    public java.lang.String getView() {
      java.lang.Object ref = view_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        view_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * A qualified view name or "#&lt;kind&gt;:&lt;qualified name&gt;" pseudo-view.
     * </pre>
     *
     * <code>string view = 2 [json_name = "view"];</code>
     * @return The bytes for view.
     */
    public com.google.protobuf.ByteString
        getViewBytes() {
      java.lang.Object ref = view_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        view_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * A qualified view name or "#&lt;kind&gt;:&lt;qualified name&gt;" pseudo-view.
     * </pre>
     *
     * <code>string view = 2 [json_name = "view"];</code>
     * @param value The view to set.
     * @return This builder for chaining.
     */
    public Builder setView(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      view_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A qualified view name or "#&lt;kind&gt;:&lt;qualified name&gt;" pseudo-view.
     * </pre>
     *
     * <code>string view = 2 [json_name = "view"];</code>
     * @return This builder for chaining.
     */
    public Builder clearView() {
      view_ = getDefaultInstance().getView();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A qualified view name or "#&lt;kind&gt;:&lt;qualified name&gt;" pseudo-view.
     * </pre>
     *
     * <code>string view = 2 [json_name = "view"];</code>
     * @param value The bytes for view to set.
     * @return This builder for chaining.
     */
    public Builder setViewBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      view_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object ports_ = "";
    /**
     * <pre>
     * "" or "minimal" (the default), or "full", as view.ParsePorts reads it.
     * </pre>
     *
     * <code>string ports = 3 [json_name = "ports"];</code>
     * @return The ports.
     */
    public java.lang.String getPorts() {
      java.lang.Object ref = ports_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ports_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * "" or "minimal" (the default), or "full", as view.ParsePorts reads it.
     * </pre>
     *
     * <code>string ports = 3 [json_name = "ports"];</code>
     * @return The bytes for ports.
     */
    public com.google.protobuf.ByteString
        getPortsBytes() {
      java.lang.Object ref = ports_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ports_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * "" or "minimal" (the default), or "full", as view.ParsePorts reads it.
     * </pre>
     *
     * <code>string ports = 3 [json_name = "ports"];</code>
     * @param value The ports to set.
     * @return This builder for chaining.
     */
    public Builder setPorts(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ports_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "" or "minimal" (the default), or "full", as view.ParsePorts reads it.
     * </pre>
     *
     * <code>string ports = 3 [json_name = "ports"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPorts() {
      ports_ = getDefaultInstance().getPorts();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "" or "minimal" (the default), or "full", as view.ParsePorts reads it.
     * </pre>
     *
     * <code>string ports = 3 [json_name = "ports"];</code>
     * @param value The bytes for ports to set.
     * @return This builder for chaining.
     */
    public Builder setPortsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ports_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sysml.RenderViewRequest)
  }

  // @@protoc_insertion_point(class_scope:sysml.RenderViewRequest)
  private static final org.openmbee.opensysml.proto.RenderViewRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.openmbee.opensysml.proto.RenderViewRequest();
  }

  public static org.openmbee.opensysml.proto.RenderViewRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RenderViewRequest>
      PARSER = new com.google.protobuf.AbstractParser<RenderViewRequest>() {
    @java.lang.Override
    public RenderViewRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RenderViewRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RenderViewRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.openmbee.opensysml.proto.RenderViewRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

