// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package org.openmbee.opensysml.proto;

@com.google.protobuf.Generated
public interface RenderGeometryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sysml.RenderGeometry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double x = 1 [json_name = "x"];</code>
   * @return The x.
   */
  double getX();

  /**
   * <code>double y = 2 [json_name = "y"];</code>
   * @return The y.
   */
  double getY();

  /**
   * <code>double width = 3 [json_name = "width"];</code>
   * @return The width.
   */
  double getWidth();

  /**
   * <code>double height = 4 [json_name = "height"];</code>
   * @return The height.
   */
  double getHeight();

  /**
   * <code>bool has_size = 5 [json_name = "hasSize"];</code>
   * @return The hasSize.
   */
  boolean getHasSize();

  /**
   * <code>bool collapsed = 6 [json_name = "collapsed"];</code>
   * @return The collapsed.
   */
  boolean getCollapsed();
}
