// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package org.openmbee.opensysml.proto;

/**
 * Protobuf type {@code sysml.ValueSequence}
 */
@com.google.protobuf.Generated
public final class ValueSequence extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:sysml.ValueSequence)
    ValueSequenceOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "ValueSequence");
  }
  // Use ValueSequence.newBuilder() to construct.
  private ValueSequence(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ValueSequence() {
    elements_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_ValueSequence_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_ValueSequence_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.openmbee.opensysml.proto.ValueSequence.class, org.openmbee.opensysml.proto.ValueSequence.Builder.class);
  }

  public static final int ELEMENTS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<org.openmbee.opensysml.proto.Value> elements_;
  /**
   * <code>repeated .sysml.Value elements = 1 [json_name = "elements"];</code>
   */
  @java.lang.Override
  public java.util.List<org.openmbee.opensysml.proto.Value> getElementsList() {
    return elements_;
  }
  /**
   * <code>repeated .sysml.Value elements = 1 [json_name = "elements"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.openmbee.opensysml.proto.ValueOrBuilder> 
      getElementsOrBuilderList() {
    return elements_;
  }
  /**
   * <code>repeated .sysml.Value elements = 1 [json_name = "elements"];</code>
   */
  @java.lang.Override
  public int getElementsCount() {
    return elements_.size();
  }
  /**
   * <code>repeated .sysml.Value elements = 1 [json_name = "elements"];</code>
   */
  @java.lang.Override
  public org.openmbee.opensysml.proto.Value getElements(int index) {
    return elements_.get(index);
  }
  /**
   * <code>repeated .sysml.Value elements = 1 [json_name = "elements"];</code>
   */
  @java.lang.Override
  public org.openmbee.opensysml.proto.ValueOrBuilder getElementsOrBuilder(
      int index) {
    return elements_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < elements_.size(); i++) {
      output.writeMessage(1, elements_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < elements_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, elements_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.openmbee.opensysml.proto.ValueSequence)) {
      return super.equals(obj);
    }
    org.openmbee.opensysml.proto.ValueSequence other = (org.openmbee.opensysml.proto.ValueSequence) obj;

    if (!getElementsList()
        .equals(other.getElementsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getElementsCount() > 0) {
      hash = (37 * hash) + ELEMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getElementsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.openmbee.opensysml.proto.ValueSequence parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmbee.opensysml.proto.ValueSequence parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.ValueSequence parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmbee.opensysml.proto.ValueSequence parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.ValueSequence parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmbee.opensysml.proto.ValueSequence parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.ValueSequence parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.openmbee.opensysml.proto.ValueSequence parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.openmbee.opensysml.proto.ValueSequence parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.openmbee.opensysml.proto.ValueSequence parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.ValueSequence parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.openmbee.opensysml.proto.ValueSequence parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.openmbee.opensysml.proto.ValueSequence prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code sysml.ValueSequence}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sysml.ValueSequence)
      org.openmbee.opensysml.proto.ValueSequenceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_ValueSequence_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_ValueSequence_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.openmbee.opensysml.proto.ValueSequence.class, org.openmbee.opensysml.proto.ValueSequence.Builder.class);
    }

    // Construct using org.openmbee.opensysml.proto.ValueSequence.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (elementsBuilder_ == null) {
        elements_ = java.util.Collections.emptyList();
      } else {
        elements_ = null;
        elementsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_ValueSequence_descriptor;
    }

    @java.lang.Override
    public org.openmbee.opensysml.proto.ValueSequence getDefaultInstanceForType() {
      return org.openmbee.opensysml.proto.ValueSequence.getDefaultInstance();
    }

    @java.lang.Override
    public org.openmbee.opensysml.proto.ValueSequence build() {
      org.openmbee.opensysml.proto.ValueSequence result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.openmbee.opensysml.proto.ValueSequence buildPartial() {
      org.openmbee.opensysml.proto.ValueSequence result = new org.openmbee.opensysml.proto.ValueSequence(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.openmbee.opensysml.proto.ValueSequence result) {
      if (elementsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          elements_ = java.util.Collections.unmodifiableList(elements_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.elements_ = elements_;
      } else {
        result.elements_ = elementsBuilder_.build();
      }
    }

    private void buildPartial0(org.openmbee.opensysml.proto.ValueSequence result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.openmbee.opensysml.proto.ValueSequence) {
        return mergeFrom((org.openmbee.opensysml.proto.ValueSequence)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.openmbee.opensysml.proto.ValueSequence other) {
      if (other == org.openmbee.opensysml.proto.ValueSequence.getDefaultInstance()) return this;
      if (elementsBuilder_ == null) {
        if (!other.elements_.isEmpty()) {
          if (elements_.isEmpty()) {
            elements_ = other.elements_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureElementsIsMutable();
            elements_.addAll(other.elements_);
          }
          onChanged();
        }
      } else {
        if (!other.elements_.isEmpty()) {
          if (elementsBuilder_.isEmpty()) {
            elementsBuilder_.dispose();
            elementsBuilder_ = null;
            elements_ = other.elements_;
            bitField0_ = (bitField0_ & ~0x00000001);
            elementsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetElementsFieldBuilder() : null;
          } else {
            elementsBuilder_.addAllMessages(other.elements_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.openmbee.opensysml.proto.Value m =
                  input.readMessage(
                      org.openmbee.opensysml.proto.Value.parser(),
                      extensionRegistry);
              if (elementsBuilder_ == null) {
                ensureElementsIsMutable();
                elements_.add(m);
              } else {
                elementsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<org.openmbee.opensysml.proto.Value> elements_ =
      java.util.Collections.emptyList();
    private void ensureElementsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        elements_ = new java.util.ArrayList<org.openmbee.opensysml.proto.Value>(elements_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        org.openmbee.opensysml.proto.Value, org.openmbee.opensysml.proto.Value.Builder, org.openmbee.opensysml.proto.ValueOrBuilder> elementsBuilder_;

    /**
     * <code>repeated .sysml.Value elements = 1 [json_name = "elements"];</code>
     */
    public java.util.List<org.openmbee.opensysml.proto.Value> getElementsList() {
      if (elementsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(elements_);
      } else {
        return elementsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .sysml.Value elements = 1 [json_name = "elements"];</code>
     */
    public int getElementsCount() {
      if (elementsBuilder_ == null) {
        return elements_.size();
      } else {
        return elementsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .sysml.Value elements = 1 [json_name = "elements"];</code>
     */
    public org.openmbee.opensysml.proto.Value getElements(int index) {
      if (elementsBuilder_ == null) {
        return elements_.get(index);
      } else {
        return elementsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .sysml.Value elements = 1 [json_name = "elements"];</code>
     */
    public Builder setElements(
        int index, org.openmbee.opensysml.proto.Value value) {
      if (elementsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureElementsIsMutable();
        elements_.set(index, value);
        onChanged();
      } else {
        elementsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .sysml.Value elements = 1 [json_name = "elements"];</code>
     */
    public Builder setElements(
        int index, org.openmbee.opensysml.proto.Value.Builder builderForValue) {
      if (elementsBuilder_ == null) {
        ensureElementsIsMutable();
        elements_.set(index, builderForValue.build());
        onChanged();
      } else {
        elementsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .sysml.Value elements = 1 [json_name = "elements"];</code>
     */
    public Builder addElements(org.openmbee.opensysml.proto.Value value) {
      if (elementsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureElementsIsMutable();
        elements_.add(value);
        onChanged();
      } else {
        elementsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .sysml.Value elements = 1 [json_name = "elements"];</code>
     */
    public Builder addElements(
        int index, org.openmbee.opensysml.proto.Value value) {
      if (elementsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureElementsIsMutable();
        elements_.add(index, value);
        onChanged();
      } else {
        elementsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .sysml.Value elements = 1 [json_name = "elements"];</code>
     */
    public Builder addElements(
        org.openmbee.opensysml.proto.Value.Builder builderForValue) {
      if (elementsBuilder_ == null) {
        ensureElementsIsMutable();
        elements_.add(builderForValue.build());
        onChanged();
      } else {
        elementsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .sysml.Value elements = 1 [json_name = "elements"];</code>
     */
    public Builder addElements(
        int index, org.openmbee.opensysml.proto.Value.Builder builderForValue) {
      if (elementsBuilder_ == null) {
        ensureElementsIsMutable();
        elements_.add(index, builderForValue.build());
        onChanged();
      } else {
        elementsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .sysml.Value elements = 1 [json_name = "elements"];</code>
     */
    public Builder addAllElements(
        java.lang.Iterable<? extends org.openmbee.opensysml.proto.Value> values) {
      if (elementsBuilder_ == null) {
        ensureElementsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, elements_);
        onChanged();
      } else {
        elementsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .sysml.Value elements = 1 [json_name = "elements"];</code>
     */
    public Builder clearElements() {
      if (elementsBuilder_ == null) {
        elements_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        elementsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .sysml.Value elements = 1 [json_name = "elements"];</code>
     */
    public Builder removeElements(int index) {
      if (elementsBuilder_ == null) {
        ensureElementsIsMutable();
        elements_.remove(index);
        onChanged();
      } else {
        elementsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .sysml.Value elements = 1 [json_name = "elements"];</code>
     */
    public org.openmbee.opensysml.proto.Value.Builder getElementsBuilder(
        int index) {
      return internalGetElementsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .sysml.Value elements = 1 [json_name = "elements"];</code>
     */
    public org.openmbee.opensysml.proto.ValueOrBuilder getElementsOrBuilder(
        int index) {
      if (elementsBuilder_ == null) {
        return elements_.get(index);  } else {
        return elementsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .sysml.Value elements = 1 [json_name = "elements"];</code>
     */
    public java.util.List<? extends org.openmbee.opensysml.proto.ValueOrBuilder> 
         getElementsOrBuilderList() {
      if (elementsBuilder_ != null) {
        return elementsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(elements_);
      }
    }
    /**
     * <code>repeated .sysml.Value elements = 1 [json_name = "elements"];</code>
     */
    public org.openmbee.opensysml.proto.Value.Builder addElementsBuilder() {
      return internalGetElementsFieldBuilder().addBuilder(
          org.openmbee.opensysml.proto.Value.getDefaultInstance());
    }
    /**
     * <code>repeated .sysml.Value elements = 1 [json_name = "elements"];</code>
     */
    public org.openmbee.opensysml.proto.Value.Builder addElementsBuilder(
        int index) {
      return internalGetElementsFieldBuilder().addBuilder(
          index, org.openmbee.opensysml.proto.Value.getDefaultInstance());
    }
    /**
     * <code>repeated .sysml.Value elements = 1 [json_name = "elements"];</code>
     */
    public java.util.List<org.openmbee.opensysml.proto.Value.Builder> 
         getElementsBuilderList() {
      return internalGetElementsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        org.openmbee.opensysml.proto.Value, org.openmbee.opensysml.proto.Value.Builder, org.openmbee.opensysml.proto.ValueOrBuilder> 
        internalGetElementsFieldBuilder() {
      if (elementsBuilder_ == null) {
        elementsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            org.openmbee.opensysml.proto.Value, org.openmbee.opensysml.proto.Value.Builder, org.openmbee.opensysml.proto.ValueOrBuilder>(
                elements_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        elements_ = null;
      }
      return elementsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:sysml.ValueSequence)
  }

  // @@protoc_insertion_point(class_scope:sysml.ValueSequence)
  private static final org.openmbee.opensysml.proto.ValueSequence DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.openmbee.opensysml.proto.ValueSequence();
  }

  public static org.openmbee.opensysml.proto.ValueSequence getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ValueSequence>
      PARSER = new com.google.protobuf.AbstractParser<ValueSequence>() {
    @java.lang.Override
    public ValueSequence parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ValueSequence> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ValueSequence> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.openmbee.opensysml.proto.ValueSequence getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

