// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package org.openmbee.opensysml.proto;

/**
 * <pre>
 * Diagnostic represents a parse/semantic error or warning
 * </pre>
 *
 * Protobuf type {@code sysml.Diagnostic}
 */
@com.google.protobuf.Generated
public final class Diagnostic extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:sysml.Diagnostic)
    DiagnosticOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "Diagnostic");
  }
  // Use Diagnostic.newBuilder() to construct.
  private Diagnostic(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Diagnostic() {
    severity_ = "";
    message_ = "";
    code_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_Diagnostic_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_Diagnostic_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.openmbee.opensysml.proto.Diagnostic.class, org.openmbee.opensysml.proto.Diagnostic.Builder.class);
  }

  private int bitField0_;
  public static final int SEVERITY_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object severity_ = "";
  /**
   * <pre>
   * "error", "warning", "info"
   * </pre>
   *
   * <code>string severity = 1 [json_name = "severity"];</code>
   * @return The severity.
   */
  @java.lang.Override
  public java.lang.String getSeverity() {
    java.lang.Object ref = severity_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      severity_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * "error", "warning", "info"
   * </pre>
   *
   * <code>string severity = 1 [json_name = "severity"];</code>
   * @return The bytes for severity.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSeverityBytes() {
    java.lang.Object ref = severity_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      severity_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object message_ = "";
  /**
   * <code>string message = 2 [json_name = "message"];</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 2 [json_name = "message"];</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SPAN_FIELD_NUMBER = 3;
  private org.openmbee.opensysml.proto.Span span_;
  /**
   * <code>.sysml.Span span = 3 [json_name = "span"];</code>
   * @return Whether the span field is set.
   */
  @java.lang.Override
  public boolean hasSpan() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.sysml.Span span = 3 [json_name = "span"];</code>
   * @return The span.
   */
  @java.lang.Override
  public org.openmbee.opensysml.proto.Span getSpan() {
    return span_ == null ? org.openmbee.opensysml.proto.Span.getDefaultInstance() : span_;
  }
  /**
   * <code>.sysml.Span span = 3 [json_name = "span"];</code>
   */
  @java.lang.Override
  public org.openmbee.opensysml.proto.SpanOrBuilder getSpanOrBuilder() {
    return span_ == null ? org.openmbee.opensysml.proto.Span.getDefaultInstance() : span_;
  }

  public static final int CODE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object code_ = "";
  /**
   * <pre>
   * Stable identifier to branch on instead of the message: a pass or rule code,
   * "syntax", "choice-point", "guard-unevaluable"; empty when none was assigned.
   * </pre>
   *
   * <code>string code = 4 [json_name = "code"];</code>
   * @return The code.
   */
  @java.lang.Override
  public java.lang.String getCode() {
    java.lang.Object ref = code_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      code_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Stable identifier to branch on instead of the message: a pass or rule code,
   * "syntax", "choice-point", "guard-unevaluable"; empty when none was assigned.
   * </pre>
   *
   * <code>string code = 4 [json_name = "code"];</code>
   * @return The bytes for code.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCodeBytes() {
    java.lang.Object ref = code_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      code_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(severity_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, severity_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, message_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getSpan());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(code_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, code_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(severity_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, severity_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, message_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getSpan());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(code_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, code_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.openmbee.opensysml.proto.Diagnostic)) {
      return super.equals(obj);
    }
    org.openmbee.opensysml.proto.Diagnostic other = (org.openmbee.opensysml.proto.Diagnostic) obj;

    if (!getSeverity()
        .equals(other.getSeverity())) return false;
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (hasSpan() != other.hasSpan()) return false;
    if (hasSpan()) {
      if (!getSpan()
          .equals(other.getSpan())) return false;
    }
    if (!getCode()
        .equals(other.getCode())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SEVERITY_FIELD_NUMBER;
    hash = (53 * hash) + getSeverity().hashCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    if (hasSpan()) {
      hash = (37 * hash) + SPAN_FIELD_NUMBER;
      hash = (53 * hash) + getSpan().hashCode();
    }
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.openmbee.opensysml.proto.Diagnostic parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmbee.opensysml.proto.Diagnostic parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.Diagnostic parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmbee.opensysml.proto.Diagnostic parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.Diagnostic parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmbee.opensysml.proto.Diagnostic parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.Diagnostic parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.openmbee.opensysml.proto.Diagnostic parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.openmbee.opensysml.proto.Diagnostic parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.openmbee.opensysml.proto.Diagnostic parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.Diagnostic parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.openmbee.opensysml.proto.Diagnostic parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.openmbee.opensysml.proto.Diagnostic prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Diagnostic represents a parse/semantic error or warning
   * </pre>
   *
   * Protobuf type {@code sysml.Diagnostic}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sysml.Diagnostic)
      org.openmbee.opensysml.proto.DiagnosticOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_Diagnostic_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_Diagnostic_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.openmbee.opensysml.proto.Diagnostic.class, org.openmbee.opensysml.proto.Diagnostic.Builder.class);
    }

    // Construct using org.openmbee.opensysml.proto.Diagnostic.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetSpanFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      severity_ = "";
      message_ = "";
      span_ = null;
      if (spanBuilder_ != null) {
        spanBuilder_.dispose();
        spanBuilder_ = null;
      }
      code_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_Diagnostic_descriptor;
    }

    @java.lang.Override
    public org.openmbee.opensysml.proto.Diagnostic getDefaultInstanceForType() {
      return org.openmbee.opensysml.proto.Diagnostic.getDefaultInstance();
    }

    @java.lang.Override
    public org.openmbee.opensysml.proto.Diagnostic build() {
      org.openmbee.opensysml.proto.Diagnostic result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.openmbee.opensysml.proto.Diagnostic buildPartial() {
      org.openmbee.opensysml.proto.Diagnostic result = new org.openmbee.opensysml.proto.Diagnostic(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.openmbee.opensysml.proto.Diagnostic result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.severity_ = severity_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.message_ = message_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.span_ = spanBuilder_ == null
            ? span_
            : spanBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.code_ = code_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.openmbee.opensysml.proto.Diagnostic) {
        return mergeFrom((org.openmbee.opensysml.proto.Diagnostic)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.openmbee.opensysml.proto.Diagnostic other) {
      if (other == org.openmbee.opensysml.proto.Diagnostic.getDefaultInstance()) return this;
      if (!other.getSeverity().isEmpty()) {
        severity_ = other.severity_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasSpan()) {
        mergeSpan(other.getSpan());
      }
      if (!other.getCode().isEmpty()) {
        code_ = other.code_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              severity_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              message_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetSpanFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              code_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object severity_ = "";
    /**
     * <pre>
     * "error", "warning", "info"
     * </pre>
     *
     * <code>string severity = 1 [json_name = "severity"];</code>
     * @return The severity.
     */
    public java.lang.String getSeverity() {
      java.lang.Object ref = severity_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        severity_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * "error", "warning", "info"
     * </pre>
     *
     * <code>string severity = 1 [json_name = "severity"];</code>
     * @return The bytes for severity.
     */
    public com.google.protobuf.ByteString
        getSeverityBytes() {
      java.lang.Object ref = severity_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        severity_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * "error", "warning", "info"
     * </pre>
     *
     * <code>string severity = 1 [json_name = "severity"];</code>
     * @param value The severity to set.
     * @return This builder for chaining.
     */
    public Builder setSeverity(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      severity_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "error", "warning", "info"
     * </pre>
     *
     * <code>string severity = 1 [json_name = "severity"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSeverity() {
      severity_ = getDefaultInstance().getSeverity();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "error", "warning", "info"
     * </pre>
     *
     * <code>string severity = 1 [json_name = "severity"];</code>
     * @param value The bytes for severity to set.
     * @return This builder for chaining.
     */
    public Builder setSeverityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      severity_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 2 [json_name = "message"];</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 2 [json_name = "message"];</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 2 [json_name = "message"];</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      message_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2 [json_name = "message"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      message_ = getDefaultInstance().getMessage();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2 [json_name = "message"];</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      message_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private org.openmbee.opensysml.proto.Span span_;
    private com.google.protobuf.SingleFieldBuilder<
        org.openmbee.opensysml.proto.Span, org.openmbee.opensysml.proto.Span.Builder, org.openmbee.opensysml.proto.SpanOrBuilder> spanBuilder_;
    /**
     * <code>.sysml.Span span = 3 [json_name = "span"];</code>
     * @return Whether the span field is set.
     */
    public boolean hasSpan() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.sysml.Span span = 3 [json_name = "span"];</code>
     * @return The span.
     */
    public org.openmbee.opensysml.proto.Span getSpan() {
      if (spanBuilder_ == null) {
        return span_ == null ? org.openmbee.opensysml.proto.Span.getDefaultInstance() : span_;
      } else {
        return spanBuilder_.getMessage();
      }
    }
    /**
     * <code>.sysml.Span span = 3 [json_name = "span"];</code>
     */
    public Builder setSpan(org.openmbee.opensysml.proto.Span value) {
      if (spanBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        span_ = value;
      } else {
        spanBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.sysml.Span span = 3 [json_name = "span"];</code>
     */
    public Builder setSpan(
        org.openmbee.opensysml.proto.Span.Builder builderForValue) {
      if (spanBuilder_ == null) {
        span_ = builderForValue.build();
      } else {
        spanBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.sysml.Span span = 3 [json_name = "span"];</code>
     */
    public Builder mergeSpan(org.openmbee.opensysml.proto.Span value) {
      if (spanBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          span_ != null &&
          span_ != org.openmbee.opensysml.proto.Span.getDefaultInstance()) {
          getSpanBuilder().mergeFrom(value);
        } else {
          span_ = value;
        }
      } else {
        spanBuilder_.mergeFrom(value);
      }
      if (span_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.sysml.Span span = 3 [json_name = "span"];</code>
     */
    public Builder clearSpan() {
      bitField0_ = (bitField0_ & ~0x00000004);
      span_ = null;
      if (spanBuilder_ != null) {
        spanBuilder_.dispose();
        spanBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.sysml.Span span = 3 [json_name = "span"];</code>
     */
    public org.openmbee.opensysml.proto.Span.Builder getSpanBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetSpanFieldBuilder().getBuilder();
    }
    /**
     * <code>.sysml.Span span = 3 [json_name = "span"];</code>
     */
    public org.openmbee.opensysml.proto.SpanOrBuilder getSpanOrBuilder() {
      if (spanBuilder_ != null) {
        return spanBuilder_.getMessageOrBuilder();
      } else {
        return span_ == null ?
            org.openmbee.opensysml.proto.Span.getDefaultInstance() : span_;
      }
    }
    /**
     * <code>.sysml.Span span = 3 [json_name = "span"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.openmbee.opensysml.proto.Span, org.openmbee.opensysml.proto.Span.Builder, org.openmbee.opensysml.proto.SpanOrBuilder> 
        internalGetSpanFieldBuilder() {
      if (spanBuilder_ == null) {
        spanBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.openmbee.opensysml.proto.Span, org.openmbee.opensysml.proto.Span.Builder, org.openmbee.opensysml.proto.SpanOrBuilder>(
                getSpan(),
                getParentForChildren(),
                isClean());
        span_ = null;
      }
      return spanBuilder_;
    }

    private java.lang.Object code_ = "";
    /**
     * <pre>
     * Stable identifier to branch on instead of the message: a pass or rule code,
     * "syntax", "choice-point", "guard-unevaluable"; empty when none was assigned.
     * </pre>
     *
     * <code>string code = 4 [json_name = "code"];</code>
     * @return The code.
     */
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        code_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Stable identifier to branch on instead of the message: a pass or rule code,
     * "syntax", "choice-point", "guard-unevaluable"; empty when none was assigned.
     * </pre>
     *
     * <code>string code = 4 [json_name = "code"];</code>
     * @return The bytes for code.
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Stable identifier to branch on instead of the message: a pass or rule code,
     * "syntax", "choice-point", "guard-unevaluable"; empty when none was assigned.
     * </pre>
     *
     * <code>string code = 4 [json_name = "code"];</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      code_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Stable identifier to branch on instead of the message: a pass or rule code,
     * "syntax", "choice-point", "guard-unevaluable"; empty when none was assigned.
     * </pre>
     *
     * <code>string code = 4 [json_name = "code"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      code_ = getDefaultInstance().getCode();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Stable identifier to branch on instead of the message: a pass or rule code,
     * "syntax", "choice-point", "guard-unevaluable"; empty when none was assigned.
     * </pre>
     *
     * <code>string code = 4 [json_name = "code"];</code>
     * @param value The bytes for code to set.
     * @return This builder for chaining.
     */
    public Builder setCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      code_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sysml.Diagnostic)
  }

  // @@protoc_insertion_point(class_scope:sysml.Diagnostic)
  private static final org.openmbee.opensysml.proto.Diagnostic DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.openmbee.opensysml.proto.Diagnostic();
  }

  public static org.openmbee.opensysml.proto.Diagnostic getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Diagnostic>
      PARSER = new com.google.protobuf.AbstractParser<Diagnostic>() {
    @java.lang.Override
    public Diagnostic parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Diagnostic> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Diagnostic> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.openmbee.opensysml.proto.Diagnostic getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

