// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package org.openmbee.opensysml.proto;

@com.google.protobuf.Generated
public interface RunAnalysisRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sysml.RunAnalysisRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string model_hash = 1 [json_name = "modelHash"];</code>
   * @return The modelHash.
   */
  java.lang.String getModelHash();
  /**
   * <code>string model_hash = 1 [json_name = "modelHash"];</code>
   * @return The bytes for modelHash.
   */
  com.google.protobuf.ByteString
      getModelHashBytes();

  /**
   * <pre>
   * FQN of the analysis case definition or usage.
   * </pre>
   *
   * <code>string symbol_id = 2 [json_name = "symbolId"];</code>
   * @return The symbolId.
   */
  java.lang.String getSymbolId();
  /**
   * <pre>
   * FQN of the analysis case definition or usage.
   * </pre>
   *
   * <code>string symbol_id = 2 [json_name = "symbolId"];</code>
   * @return The bytes for symbolId.
   */
  com.google.protobuf.ByteString
      getSymbolIdBytes();

  /**
   * <pre>
   * Optional FQN of a part/usage to instantiate as the case's subject. Empty
   * leaves the case's own `subject s = ...` binding to supply it; a case that
   * binds none and is given none fails to run.
   * </pre>
   *
   * <code>string subject_symbol_id = 3 [json_name = "subjectSymbolId"];</code>
   * @return The subjectSymbolId.
   */
  java.lang.String getSubjectSymbolId();
  /**
   * <pre>
   * Optional FQN of a part/usage to instantiate as the case's subject. Empty
   * leaves the case's own `subject s = ...` binding to supply it; a case that
   * binds none and is given none fails to run.
   * </pre>
   *
   * <code>string subject_symbol_id = 3 [json_name = "subjectSymbolId"];</code>
   * @return The bytes for subjectSymbolId.
   */
  com.google.protobuf.ByteString
      getSubjectSymbolIdBytes();

  /**
   * <pre>
   * Positional arguments for the case's input parameters, in declaration order;
   * the subject is never among them.
   * </pre>
   *
   * <code>repeated .sysml.Value arguments = 4 [json_name = "arguments"];</code>
   */
  java.util.List<org.openmbee.opensysml.proto.Value> 
      getArgumentsList();
  /**
   * <pre>
   * Positional arguments for the case's input parameters, in declaration order;
   * the subject is never among them.
   * </pre>
   *
   * <code>repeated .sysml.Value arguments = 4 [json_name = "arguments"];</code>
   */
  org.openmbee.opensysml.proto.Value getArguments(int index);
  /**
   * <pre>
   * Positional arguments for the case's input parameters, in declaration order;
   * the subject is never among them.
   * </pre>
   *
   * <code>repeated .sysml.Value arguments = 4 [json_name = "arguments"];</code>
   */
  int getArgumentsCount();
  /**
   * <pre>
   * Positional arguments for the case's input parameters, in declaration order;
   * the subject is never among them.
   * </pre>
   *
   * <code>repeated .sysml.Value arguments = 4 [json_name = "arguments"];</code>
   */
  java.util.List<? extends org.openmbee.opensysml.proto.ValueOrBuilder> 
      getArgumentsOrBuilderList();
  /**
   * <pre>
   * Positional arguments for the case's input parameters, in declaration order;
   * the subject is never among them.
   * </pre>
   *
   * <code>repeated .sysml.Value arguments = 4 [json_name = "arguments"];</code>
   */
  org.openmbee.opensysml.proto.ValueOrBuilder getArgumentsOrBuilder(
      int index);

  /**
   * <pre>
   * Arguments bound to input parameters by name.
   * </pre>
   *
   * <code>map&lt;string, .sysml.Value&gt; named_arguments = 5 [json_name = "namedArguments"];</code>
   */
  int getNamedArgumentsCount();
  /**
   * <pre>
   * Arguments bound to input parameters by name.
   * </pre>
   *
   * <code>map&lt;string, .sysml.Value&gt; named_arguments = 5 [json_name = "namedArguments"];</code>
   */
  boolean containsNamedArguments(
      java.lang.String key);
  /**
   * Use {@link #getNamedArgumentsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, org.openmbee.opensysml.proto.Value>
  getNamedArguments();
  /**
   * <pre>
   * Arguments bound to input parameters by name.
   * </pre>
   *
   * <code>map&lt;string, .sysml.Value&gt; named_arguments = 5 [json_name = "namedArguments"];</code>
   */
  java.util.Map<java.lang.String, org.openmbee.opensysml.proto.Value>
  getNamedArgumentsMap();
  /**
   * <pre>
   * Arguments bound to input parameters by name.
   * </pre>
   *
   * <code>map&lt;string, .sysml.Value&gt; named_arguments = 5 [json_name = "namedArguments"];</code>
   */
  /* nullable */
org.openmbee.opensysml.proto.Value getNamedArgumentsOrDefault(
      java.lang.String key,
      /* nullable */
org.openmbee.opensysml.proto.Value defaultValue);
  /**
   * <pre>
   * Arguments bound to input parameters by name.
   * </pre>
   *
   * <code>map&lt;string, .sysml.Value&gt; named_arguments = 5 [json_name = "namedArguments"];</code>
   */
  org.openmbee.opensysml.proto.Value getNamedArgumentsOrThrow(
      java.lang.String key);

  /**
   * <pre>
   * Scheduling policy the run resolves its choice points under: "declared",
   * "reverse", "seed:&lt;n&gt;" or "explore[:runs=&lt;n&gt;,depth=&lt;d&gt;]". Empty is the
   * default, "reverse"; any other spelling is INVALID_ARGUMENT. Under explore
   * the response answers with `outcomes` and `exploration` in place of one run's
   * outputs, verdicts, instances and error (see ExecuteActionResponse).
   * </pre>
   *
   * <code>string schedule = 6 [json_name = "schedule"];</code>
   * @return The schedule.
   */
  java.lang.String getSchedule();
  /**
   * <pre>
   * Scheduling policy the run resolves its choice points under: "declared",
   * "reverse", "seed:&lt;n&gt;" or "explore[:runs=&lt;n&gt;,depth=&lt;d&gt;]". Empty is the
   * default, "reverse"; any other spelling is INVALID_ARGUMENT. Under explore
   * the response answers with `outcomes` and `exploration` in place of one run's
   * outputs, verdicts, instances and error (see ExecuteActionResponse).
   * </pre>
   *
   * <code>string schedule = 6 [json_name = "schedule"];</code>
   * @return The bytes for schedule.
   */
  com.google.protobuf.ByteString
      getScheduleBytes();
}
