// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package org.openmbee.opensysml.proto;

@com.google.protobuf.Generated
public interface RunSweepRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sysml.RunSweepRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string model_hash = 1 [json_name = "modelHash"];</code>
   * @return The modelHash.
   */
  java.lang.String getModelHash();
  /**
   * <code>string model_hash = 1 [json_name = "modelHash"];</code>
   * @return The bytes for modelHash.
   */
  com.google.protobuf.ByteString
      getModelHashBytes();

  /**
   * <pre>
   * FQN of the analysis case or calc, definition or usage.
   * </pre>
   *
   * <code>string symbol_id = 2 [json_name = "symbolId"];</code>
   * @return The symbolId.
   */
  java.lang.String getSymbolId();
  /**
   * <pre>
   * FQN of the analysis case or calc, definition or usage.
   * </pre>
   *
   * <code>string symbol_id = 2 [json_name = "symbolId"];</code>
   * @return The bytes for symbolId.
   */
  com.google.protobuf.ByteString
      getSymbolIdBytes();

  /**
   * <pre>
   * Optional FQN of a part/usage to instantiate as an analysis case's subject.
   * </pre>
   *
   * <code>string subject_symbol_id = 3 [json_name = "subjectSymbolId"];</code>
   * @return The subjectSymbolId.
   */
  java.lang.String getSubjectSymbolId();
  /**
   * <pre>
   * Optional FQN of a part/usage to instantiate as an analysis case's subject.
   * </pre>
   *
   * <code>string subject_symbol_id = 3 [json_name = "subjectSymbolId"];</code>
   * @return The bytes for subjectSymbolId.
   */
  com.google.protobuf.ByteString
      getSubjectSymbolIdBytes();

  /**
   * <pre>
   * Positional arguments for the target's input parameters, in declaration
   * order, as every row binds them.
   * </pre>
   *
   * <code>repeated .sysml.Value arguments = 4 [json_name = "arguments"];</code>
   */
  java.util.List<org.openmbee.opensysml.proto.Value> 
      getArgumentsList();
  /**
   * <pre>
   * Positional arguments for the target's input parameters, in declaration
   * order, as every row binds them.
   * </pre>
   *
   * <code>repeated .sysml.Value arguments = 4 [json_name = "arguments"];</code>
   */
  org.openmbee.opensysml.proto.Value getArguments(int index);
  /**
   * <pre>
   * Positional arguments for the target's input parameters, in declaration
   * order, as every row binds them.
   * </pre>
   *
   * <code>repeated .sysml.Value arguments = 4 [json_name = "arguments"];</code>
   */
  int getArgumentsCount();
  /**
   * <pre>
   * Positional arguments for the target's input parameters, in declaration
   * order, as every row binds them.
   * </pre>
   *
   * <code>repeated .sysml.Value arguments = 4 [json_name = "arguments"];</code>
   */
  java.util.List<? extends org.openmbee.opensysml.proto.ValueOrBuilder> 
      getArgumentsOrBuilderList();
  /**
   * <pre>
   * Positional arguments for the target's input parameters, in declaration
   * order, as every row binds them.
   * </pre>
   *
   * <code>repeated .sysml.Value arguments = 4 [json_name = "arguments"];</code>
   */
  org.openmbee.opensysml.proto.ValueOrBuilder getArgumentsOrBuilder(
      int index);

  /**
   * <pre>
   * Arguments bound to input parameters by name, as every row binds them.
   * </pre>
   *
   * <code>map&lt;string, .sysml.Value&gt; named_arguments = 5 [json_name = "namedArguments"];</code>
   */
  int getNamedArgumentsCount();
  /**
   * <pre>
   * Arguments bound to input parameters by name, as every row binds them.
   * </pre>
   *
   * <code>map&lt;string, .sysml.Value&gt; named_arguments = 5 [json_name = "namedArguments"];</code>
   */
  boolean containsNamedArguments(
      java.lang.String key);
  /**
   * Use {@link #getNamedArgumentsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, org.openmbee.opensysml.proto.Value>
  getNamedArguments();
  /**
   * <pre>
   * Arguments bound to input parameters by name, as every row binds them.
   * </pre>
   *
   * <code>map&lt;string, .sysml.Value&gt; named_arguments = 5 [json_name = "namedArguments"];</code>
   */
  java.util.Map<java.lang.String, org.openmbee.opensysml.proto.Value>
  getNamedArgumentsMap();
  /**
   * <pre>
   * Arguments bound to input parameters by name, as every row binds them.
   * </pre>
   *
   * <code>map&lt;string, .sysml.Value&gt; named_arguments = 5 [json_name = "namedArguments"];</code>
   */
  /* nullable */
org.openmbee.opensysml.proto.Value getNamedArgumentsOrDefault(
      java.lang.String key,
      /* nullable */
org.openmbee.opensysml.proto.Value defaultValue);
  /**
   * <pre>
   * Arguments bound to input parameters by name, as every row binds them.
   * </pre>
   *
   * <code>map&lt;string, .sysml.Value&gt; named_arguments = 5 [json_name = "namedArguments"];</code>
   */
  org.openmbee.opensysml.proto.Value getNamedArgumentsOrThrow(
      java.lang.String key);

  /**
   * <pre>
   * The ranges swept, which several of make one row per point of their
   * cartesian product, the first varying slowest.
   * </pre>
   *
   * <code>repeated .sysml.SweepRange ranges = 6 [json_name = "ranges"];</code>
   */
  java.util.List<org.openmbee.opensysml.proto.SweepRange> 
      getRangesList();
  /**
   * <pre>
   * The ranges swept, which several of make one row per point of their
   * cartesian product, the first varying slowest.
   * </pre>
   *
   * <code>repeated .sysml.SweepRange ranges = 6 [json_name = "ranges"];</code>
   */
  org.openmbee.opensysml.proto.SweepRange getRanges(int index);
  /**
   * <pre>
   * The ranges swept, which several of make one row per point of their
   * cartesian product, the first varying slowest.
   * </pre>
   *
   * <code>repeated .sysml.SweepRange ranges = 6 [json_name = "ranges"];</code>
   */
  int getRangesCount();
  /**
   * <pre>
   * The ranges swept, which several of make one row per point of their
   * cartesian product, the first varying slowest.
   * </pre>
   *
   * <code>repeated .sysml.SweepRange ranges = 6 [json_name = "ranges"];</code>
   */
  java.util.List<? extends org.openmbee.opensysml.proto.SweepRangeOrBuilder> 
      getRangesOrBuilderList();
  /**
   * <pre>
   * The ranges swept, which several of make one row per point of their
   * cartesian product, the first varying slowest.
   * </pre>
   *
   * <code>repeated .sysml.SweepRange ranges = 6 [json_name = "ranges"];</code>
   */
  org.openmbee.opensysml.proto.SweepRangeOrBuilder getRangesOrBuilder(
      int index);

  /**
   * <pre>
   * Rows to draw uniformly from each range instead of stepping through it. 0
   * steps through them; above 0 needs a seed and refuses a range with a step.
   * </pre>
   *
   * <code>int64 samples = 7 [json_name = "samples"];</code>
   * @return The samples.
   */
  long getSamples();

  /**
   * <pre>
   * Seed the draws are taken from: the same seed draws the same table on every
   * platform. Required with `samples`, ignored without it.
   * </pre>
   *
   * <code>uint64 seed = 8 [json_name = "seed"];</code>
   * @return The seed.
   */
  long getSeed();
}
